#Import modules

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

#Data

In [3]:
data = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/transcriptomics_tpm_benedetti.csv', index_col = 0)
data

,MSKC-00397,MSKC-00399,MSKC-00400,MSKC-00404,MSKC-00405,MSKC-00406,MSKC-00407,MSKC-00412,MSKC-00441,MSKC-00417,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
A1BG,1.304026,1.928762,0.869958,1.880487,1.660118,0.892479,3.436963,2.064896,1.094232,1.749509,...,0.785316,0.977454,0.447450,0.441843,0.662409,0.707219,1.137666,1.488923,1.871112,0.455020
A2M,320.190822,599.699496,759.630310,530.494017,1391.019172,609.172144,53.390407,1413.895848,397.963961,628.208954,...,210.888701,47.498667,76.943934,82.257362,20.723809,20.692371,7.208059,29.921821,21.872767,18.733246
A2MP1,4.301926,1.251719,1.620558,1.792046,1.391611,1.381162,0.117595,3.033230,0.000000,0.914209,...,0.140536,0.052223,0.064615,0.182036,0.360108,0.106965,0.230259,0.361582,0.542156,0.085702
NAT1,8.314472,10.039836,5.763073,8.030295,4.538719,6.406598,3.772830,5.862423,6.280781,7.421067,...,0.211574,0.092810,0.157897,0.179032,0.039136,0.025922,0.033360,0.028881,0.071372,0.032459
NAT2,0.964676,3.234161,0.369455,0.605261,0.396575,0.139946,0.000000,0.240528,0.000000,0.347369,...,0.071581,0.014564,0.105301,0.100544,0.036846,0.009220,0.011865,0.057782,0.019039,0.026642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MAFIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TP53TG3B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SNAR-A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIR4509-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTY8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
gene_names = pd.read_csv('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/BulkRNABert_data/benedetti_mart_export.txt', sep = '\t', index_col= 1)
gene_names.index.name = None
gene_names

           Gene stable ID
MT-ND1    ENSG00000198888
MT-ND2    ENSG00000198763
MT-CO1    ENSG00000198804
MT-TS1    ENSG00000210151
MT-CO2    ENSG00000198712
...                   ...
AHCYL1    ENSG00000168710
JMJD4     ENSG00000081692
TNFRSF14  ENSG00000157873
DAP3      ENSG00000132676
YY1AP1    ENSG00000163374

[42601 rows x 1 columns]

In [5]:
gene_names_dict = gene_names['Gene stable ID'].to_dict()
len(gene_names_dict)

37246

In [6]:
data['name'] = data.index.map(gene_names_dict)
data = data.dropna(subset = ['name'])
data = data.set_index('name')
data.index.name = None
data

,MSKC-00397,MSKC-00399,MSKC-00400,MSKC-00404,MSKC-00405,MSKC-00406,MSKC-00407,MSKC-00412,MSKC-00441,MSKC-00417,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
ENSG00000121410,1.304026,1.928762,0.869958,1.880487,1.660118,0.892479,3.436963,2.064896,1.094232,1.749509,...,0.785316,0.977454,0.447450,0.441843,0.662409,0.707219,1.137666,1.488923,1.871112,0.455020
ENSG00000175899,320.190822,599.699496,759.630310,530.494017,1391.019172,609.172144,53.390407,1413.895848,397.963961,628.208954,...,210.888701,47.498667,76.943934,82.257362,20.723809,20.692371,7.208059,29.921821,21.872767,18.733246
ENSG00000291190,4.301926,1.251719,1.620558,1.792046,1.391611,1.381162,0.117595,3.033230,0.000000,0.914209,...,0.140536,0.052223,0.064615,0.182036,0.360108,0.106965,0.230259,0.361582,0.542156,0.085702
ENSG00000171428,8.314472,10.039836,5.763073,8.030295,4.538719,6.406598,3.772830,5.862423,6.280781,7.421067,...,0.211574,0.092810,0.157897,0.179032,0.039136,0.025922,0.033360,0.028881,0.071372,0.032459
ENSG00000156006,0.964676,3.234161,0.369455,0.605261,0.396575,0.139946,0.000000,0.240528,0.000000,0.347369,...,0.071581,0.014564,0.105301,0.100544,0.036846,0.009220,0.011865,0.057782,0.019039,0.026642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000291012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000274847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000261509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000276941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000183385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
save_data = data.T
save_data.to_csv('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/gene_expression_benedetti_dataset.csv')

In [ ]:
with open("drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/BulkRNABert_data/common_gene_id.txt") as f:
    gene_list = [line.strip() for line in f]

print(len(gene_list))

19062

In [ ]:
genes_not_found_in_data = [gene for gene in gene_list if gene not in data.index]
len(genes_not_found_in_data)

886

In [ ]:
for i in genes_not_found_in_data:
  data.loc[i] = np.nan
data

,MSKC-00397,MSKC-00399,MSKC-00400,MSKC-00404,MSKC-00405,MSKC-00406,MSKC-00407,MSKC-00412,MSKC-00441,MSKC-00417,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
ENSG00000121410,1.304026,1.928762,0.869958,1.880487,1.660118,0.892479,3.436963,2.064896,1.094232,1.749509,...,0.785316,0.977454,0.447450,0.441843,0.662409,0.707219,1.137666,1.488923,1.871112,0.455020
ENSG00000175899,320.190822,599.699496,759.630310,530.494017,1391.019172,609.172144,53.390407,1413.895848,397.963961,628.208954,...,210.888701,47.498667,76.943934,82.257362,20.723809,20.692371,7.208059,29.921821,21.872767,18.733246
ENSG00000291190,4.301926,1.251719,1.620558,1.792046,1.391611,1.381162,0.117595,3.033230,0.000000,0.914209,...,0.140536,0.052223,0.064615,0.182036,0.360108,0.106965,0.230259,0.361582,0.542156,0.085702
ENSG00000171428,8.314472,10.039836,5.763073,8.030295,4.538719,6.406598,3.772830,5.862423,6.280781,7.421067,...,0.211574,0.092810,0.157897,0.179032,0.039136,0.025922,0.033360,0.028881,0.071372,0.032459
ENSG00000156006,0.964676,3.234161,0.369455,0.605261,0.396575,0.139946,0.000000,0.240528,0.000000,0.347369,...,0.071581,0.014564,0.105301,0.100544,0.036846,0.009220,0.011865,0.057782,0.019039,0.026642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000284535,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data = data.loc[gene_list]
data

,MSKC-00397,MSKC-00399,MSKC-00400,MSKC-00404,MSKC-00405,MSKC-00406,MSKC-00407,MSKC-00412,MSKC-00441,MSKC-00417,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
ENSG00000000003,87.492331,126.939144,46.151968,43.768328,101.558497,57.049585,104.417869,34.117635,78.851628,58.777470,...,9.966736,13.327122,8.930549,12.707505,3.584807,2.926636,2.765044,2.467863,2.299435,2.727859
ENSG00000000005,0.083832,0.991959,0.642128,0.078898,0.482484,0.030404,0.046596,0.705454,0.083074,0.060374,...,0.058254,0.086669,0.063298,0.426596,0.081213,0.024386,0.117687,0.095518,0.037768,0.039638
ENSG00000000419,119.085084,102.072551,121.438296,100.218984,101.428590,107.843656,132.247301,97.491951,163.586596,90.555546,...,2.353124,2.927943,3.603287,2.236585,4.519664,3.544263,2.837619,1.654335,3.951971,3.931738
ENSG00000000457,10.729475,13.968331,11.219856,10.260763,10.976298,8.715105,5.029246,10.448204,8.378585,8.679668,...,2.005479,2.307210,1.944361,1.948941,2.225704,1.864470,1.752504,1.146944,2.310034,1.522523
ENSG00000000460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000284564,306.711498,210.691766,347.973049,421.511982,371.932961,336.502351,149.790596,220.782408,236.538003,219.038393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284596,5.377687,0.000000,15.446746,15.183403,13.264478,7.313823,2.241764,8.799299,1.998401,4.357002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data = data.reindex(gene_list)
data

,MSKC-00397,MSKC-00399,MSKC-00400,MSKC-00404,MSKC-00405,MSKC-00406,MSKC-00407,MSKC-00412,MSKC-00441,MSKC-00417,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
ENSG00000000003,87.492331,126.939144,46.151968,43.768328,101.558497,57.049585,104.417869,34.117635,78.851628,58.777470,...,9.966736,13.327122,8.930549,12.707505,3.584807,2.926636,2.765044,2.467863,2.299435,2.727859
ENSG00000000005,0.083832,0.991959,0.642128,0.078898,0.482484,0.030404,0.046596,0.705454,0.083074,0.060374,...,0.058254,0.086669,0.063298,0.426596,0.081213,0.024386,0.117687,0.095518,0.037768,0.039638
ENSG00000000419,119.085084,102.072551,121.438296,100.218984,101.428590,107.843656,132.247301,97.491951,163.586596,90.555546,...,2.353124,2.927943,3.603287,2.236585,4.519664,3.544263,2.837619,1.654335,3.951971,3.931738
ENSG00000000457,10.729475,13.968331,11.219856,10.260763,10.976298,8.715105,5.029246,10.448204,8.378585,8.679668,...,2.005479,2.307210,1.944361,1.948941,2.225704,1.864470,1.752504,1.146944,2.310034,1.522523
ENSG00000000460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000284564,306.711498,210.691766,347.973049,421.511982,371.932961,336.502351,149.790596,220.782408,236.538003,219.038393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000284596,5.377687,0.000000,15.446746,15.183403,13.264478,7.313823,2.241764,8.799299,1.998401,4.357002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Assert gene order
good = []
for i in data.index:
  for j in gene_list:
    if i == j:
      good.append(i)
len(good)

19062

In [ ]:
data.to_csv('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/BulkRNABert_data/benedetti_processed_for_bulkrnabert.csv', index = True)