#Import modules

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

#Data

In [3]:
sample_annot = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/MasterMapping_MetImmune_03_16_2022_release.csv')
sample_annot

,CommonID,MetabID,ITHID,RNAID,MetabFile,MetabFile_sheet,ITHFile,RNAFile,RNA_raw_File,Dataset,Histology,TN,Identifier
0,OV:P1,P1,GSM642933_OC01_ARN0001_s1h1s1_U133p2.CEL.gz,GSM642933_OC01_ARN0001_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
1,OV:P2,P2,GSM642966_OC01_ARN0049_s2h1s1_U133p2.CEL.gz,GSM642966_OC01_ARN0049_s2h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
2,OV:P41,P41,GSM642979_OC01_ARN0072_s1h1s1_U133p2.CEL.gz,GSM642979_OC01_ARN0072_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
3,OV:P42,P42,GSM643007_OC01_ARN0118_s1h1s1_U133p2.CEL.gz,GSM643007_OC01_ARN0118_s1h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
4,OV:P43,P43,GSM642949_OC01_ARN0026_s2h1s1_U133p2.CEL.gz,GSM642949_OC01_ARN0026_s2h1s1_U133p2.CEL.gz,PreprocessedData_OV.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE26193.csv,GSE26193.hgu133plus2.gene_symbol.csv,GSE26193.hgu133plus2.gene_symbol.csv,OV,HGSOC,Tumor,OV
...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,LiCa2:LCS_683,LCS_683,GSM1979661_D6_683A.CEL.gz,GSM1979661_D6_683A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
984,LiCa2:LCS_684,LCS_684,GSM1979663_B5_684A.CEL.gz,GSM1979663_B5_684A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
985,LiCa2:LCS_685,LCS_685,GSM1979665_H4_685A.CEL.gz,GSM1979665_H4_685A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
986,LiCa2:LCS_687,LCS_687,GSM1979667_D6_687A.CEL.gz,GSM1979667_D6_687A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2
987,LiCa2:LCS_688,LCS_688,GSM1979669_F1_688A.CEL.gz,GSM1979669_F1_688A.CEL.gz,PreprocessedData_ICC.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.GSE76297.csv,GSE76297.hugene20st.gene_symbol.csv,GSE76297.hugene20st.gene_symbol.csv,ICC,CCA,Tumor,LiCa2

In [4]:
tpm_rna_files = []
for file_name in list(sample_annot.RNAFile.unique()):
  if file_name.endswith('.tpm.gene_symbol.csv'):
    tpm_rna_files.append(file_name)
tpm_rna_files

['Flow4Batch.tpm.gene_symbol.csv',
 'MultiRegionalRCC.tpm.gene_symbol.csv',
 'Project_08402_M.tpm.gene_symbol.csv',
 'HCC.tpm.gene_symbol.csv',
 'Cornell_DLBCL.tpm.gene_symbol.csv',
 'PMC4187326_BRCA.tpm.gene_symbol.csv',
 'Multiregions.2Batchs.Sample.hg19KnownGene.tpm.gene_symbol.csv',
 'CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol.csv']

In [5]:
import os

file_names_tpm = []
for file in os.listdir('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/transcriptomics_processed'):
  if file in tpm_rna_files:
    file_names_tpm.append(file)
file_names_tpm

['CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol.csv',
 'Cornell_DLBCL.tpm.gene_symbol.csv',
 'MultiRegionalRCC.tpm.gene_symbol.csv',
 'Project_08402_M.tpm.gene_symbol.csv',
 'Flow4Batch.tpm.gene_symbol.csv',
 'PMC4187326_BRCA.tpm.gene_symbol.csv',
 'HCC.tpm.gene_symbol.csv',
 'Multiregions.2Batchs.Sample.hg19KnownGene.tpm.gene_symbol.csv']

In [6]:
sample_annot_tpm = sample_annot[sample_annot.RNAFile.isin(file_names_tpm)]
sample_annot_tpm

,CommonID,MetabID,ITHID,RNAID,MetabFile,MetabFile_sheet,ITHFile,RNAFile,RNA_raw_File,Dataset,Histology,TN,Identifier
45,RC18:MSKC-00397,MSKC-00397,RCC483,RCC483,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow
46,RC18:MSKC-00399,MSKC-00399,RCC486,RCC486,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Metanphric Adenoma,Tumor,RC18Flow
47,RC18:MSKC-00400,MSKC-00400,RCC495,RCC495,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow
48,RC18:MSKC-00404,MSKC-00404,RCC539,RCC539,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow
49,RC18:MSKC-00405,MSKC-00405,RCC540,RCC540,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow
...,...,...,...,...,...,...,...,...,...,...,...,...,...
843,GBM:PT-P44H,PT-P44H,PT-P44H,PT-P44H,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM
844,GBM:PT-R55F,PT-R55F,PT-R55F,PT-R55F,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM
845,GBM:PT-RN5K,PT-RN5K,PT-RN5K,PT-RN5K,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM
846,GBM:PT-UTHO,PT-UTHO,PT-UTHO,PT-UTHO,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM
847,GBM:PT-WVLH,PT-WVLH,PT-WVLH,PT-WVLH,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM

In [7]:
sample_annot_tpm['SampleID'] = ['Sample_' + str(i) for i in range(len(sample_annot_tpm))]
sample_annot_tpm

/tmp/ipython-input-3994757641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_annot_tpm['SampleID'] = ['Sample_' + str(i) for i in range(len(sample_annot_tpm))]

,CommonID,MetabID,ITHID,RNAID,MetabFile,MetabFile_sheet,ITHFile,RNAFile,RNA_raw_File,Dataset,Histology,TN,Identifier,SampleID
45,RC18:MSKC-00397,MSKC-00397,RCC483,RCC483,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow,Sample_0
46,RC18:MSKC-00399,MSKC-00399,RCC486,RCC486,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Metanphric Adenoma,Tumor,RC18Flow,Sample_1
47,RC18:MSKC-00400,MSKC-00400,RCC495,RCC495,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow,Sample_2
48,RC18:MSKC-00404,MSKC-00404,RCC539,RCC539,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow,Sample_3
49,RC18:MSKC-00405,MSKC-00405,RCC540,RCC540,PreprocessedData_ccRCC2.xlsx,metabo_imputed_filtered_Tumor,MergedDeconvolution.Flow4Batch.csv,Flow4Batch.tpm.gene_symbol.csv,Flow4Batch.raw.gene_symbol.csv,ccRCC2,Clear Cell,Tumor,RC18Flow,Sample_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
843,GBM:PT-P44H,PT-P44H,PT-P44H,PT-P44H,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM,Sample_438
844,GBM:PT-R55F,PT-R55F,PT-R55F,PT-R55F,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM,Sample_439
845,GBM:PT-RN5K,PT-RN5K,PT-RN5K,PT-RN5K,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM,Sample_440
846,GBM:PT-UTHO,PT-UTHO,PT-UTHO,PT-UTHO,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM,Sample_441
847,GBM:PT-WVLH,PT-WVLH,PT-WVLH,PT-WVLH,PreprocessedData_GBM.xlsx,metabo_imputed_filtered_Normal,MergedDeconvolution.CPTAC_GBM.csv,CPTAC_GBM_htseq_rna_04_09_2021.tpm.gene_symbol...,CPTAC_GBM_htseq_rna_04_09_2021.raw.gene_symbol...,GBM,GBM,Normal,GBM,Sample_442

In [8]:
merged_transcriptomics = pd.DataFrame()
for i in file_names_tpm:
  file_read = pd.read_csv(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/transcriptomics_processed/{i}')
  file_read = file_read.set_index('gene_symbol')
  file_read.index.name = None

  # Check for overlapping columns and only add new ones
  new_cols = [col for col in file_read.columns if col not in merged_transcriptomics.columns]
  merged_transcriptomics = pd.concat([merged_transcriptomics, file_read[new_cols]], axis='columns')

merged_transcriptomics

,C3L-02704,C3N-03180,C3N-03183,C3N-02188,C3N-01851,C3L-03266,C3L-02465,C3N-02788,C3L-01887,PT-Y8DK,...,MSK1170,MSK1171,MSK1172,MSK1173,MSK1174,MSK1175,MSK1176,MSK1177,MSK1178,MSK1179
A1BG,0.634935,0.727131,0.785316,0.505794,0.276903,1.252584,0.153516,0.524860,0.923377,0.398826,...,4.490258,12.147058,41.010469,28.207853,7.220787,5.224010,5.328874,3.984721,8.760791,2.166899
A2M,151.737457,147.600144,210.888701,111.010935,235.438260,64.097423,95.012084,130.398983,33.202590,20.238386,...,1005.974244,108.202814,108.894907,932.774567,641.069774,459.770011,1263.791029,836.423379,367.761840,380.446899
A2MP1,0.193512,0.136392,0.140536,0.058927,0.196886,0.045927,0.051193,0.549248,0.066810,0.089846,...,4.538414,12.295716,33.117522,32.315528,7.167903,2.416043,5.154209,4.196392,4.010646,2.209165
NAT1,0.079923,0.142145,0.211574,0.138149,0.173220,0.088151,0.309583,0.250686,0.081831,0.023702,...,6.460310,11.882165,25.881217,23.154891,3.694304,2.478461,4.493837,3.840836,3.519603,4.023029
NAT2,0.103370,0.047897,0.071581,0.136710,0.221798,0.052256,0.040449,0.224881,0.059923,0.019966,...,0.394160,4.905566,16.413350,17.969030,0.290514,0.084740,2.088992,0.263916,0.098848,0.179074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MAFIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TP53TG3B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SNAR-A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
MIR4509-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
TTTY8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.303598,0.814176,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [9]:
sample_annot_tpm.Dataset.unique()

array(['ccRCC2', 'ccRCC3', 'ccRCC1', 'HurthleCC', 'DLBCL', 'BRCA2',
       'ccRCC4', 'GBM'], dtype=object)

In [10]:
file_names_metabolomics = []
for file in os.listdir('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/metabolomics_processed'):
  for dataset in list(sample_annot_tpm.Dataset.unique()):
    if file.endswith(f'{dataset}.xlsx'):
      file_names_metabolomics.append(file)
    else:
      pass
file_names_metabolomics

['PreprocessedData_BRCA2.xlsx',
 'PreprocessedData_DLBCL.xlsx',
 'PreprocessedData_ccRCC2.xlsx',
 'PreprocessedData_ccRCC1.xlsx',
 'PreprocessedData_GBM.xlsx',
 'PreprocessedData_ccRCC3.xlsx',
 'PreprocessedData_ccRCC4.xlsx',
 'PreprocessedData_HurthleCC.xlsx']

In [11]:
file_len = []
for i in file_names_metabolomics:
  file_read = pd.read_excel(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/metabolomics_processed/{i}', sheet_name= 'data_imputed')
  file_len.append(len(file_read))

file_len

[399, 751, 787, 877, 713, 787, 1030, 737]

In [12]:
merged_metabolomics = pd.DataFrame()
for i in file_names_metabolomics:
  file_read = pd.read_excel(f'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/pancancer_metabolomics_v.0.3.4/pancancer_metabolomics/data/metabolomics_processed/{i}', sheet_name= 'data_imputed')
  file_read = file_read.set_index('Unnamed: 0')
  file_read.index.name = None

  # Check for overlapping columns and only add new ones
  new_cols = [col for col in file_read.columns if col not in merged_metabolomics.columns]
  merged_metabolomics = pd.concat([merged_metabolomics, file_read[new_cols]], axis='columns')


merged_metabolomics

,DUKE-00650,DUKE-00651,DUKE-00652,DUKE-00653,DUKE-00654,DUKE-00655,DUKE-00656,DUKE-00657,DUKE-00658,DUKE-00659,...,MSKC-00509,MSKC-00510,MSKC-00511,MSKC-00512,MSKC-00513,MSKC-00514,MSKC-00515,MSKC-00516,MSKC-00517,MSKC-00518
"1,2-propanediol",17.728228,21.037723,23.959087,20.682481,19.963768,21.372052,22.014168,19.677653,24.311710,20.759181,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"1,5-anhydroglucitol (1,5-AG)",18.277058,19.394321,19.044231,19.193116,19.653941,20.689711,21.530143,20.145794,19.355534,20.459938,...,19.671671,19.942660,19.109263,21.212509,19.543751,20.379484,20.341078,20.704356,21.140079,20.368759
1-arachidonoyl-GPC (20:4n6),16.156080,17.671134,14.631118,15.608743,15.383235,17.552577,20.094256,17.854153,16.278081,17.749451,...,21.087915,18.768551,20.386266,20.345652,18.996681,19.421492,19.173876,20.163745,18.981320,19.517331
1-arachidonoyl-GPE (20:4n6),15.611096,14.233610,16.423374,14.400485,15.369813,15.128236,15.261825,14.785590,15.876500,15.822026,...,21.485228,18.825094,20.793490,20.777254,21.021257,21.356679,21.246617,21.047280,21.044059,21.383338
1-arachidonoyl-GPI (20:4),15.675876,14.384728,16.305192,15.299840,14.913759,14.744934,15.269355,14.445883,15.213580,15.213400,...,21.699653,16.561325,22.987743,19.159835,19.978780,19.943406,19.794728,21.413212,19.923369,21.212340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nicotinate ribonucleoside,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.876410,15.876410,17.846155,17.567851,15.876410,15.876410,15.876410,15.876410,15.876410,18.117871
norfluoxetine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796
palmitoleoyl ethanolamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.495232,15.366567,14.866441,13.940225,13.940225,15.493134,14.380336,13.940225,13.940225,15.814253
succinimide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.195469,16.846666,18.709706,15.167041,19.089354,17.341559,16.871599,19.378768,16.766302,15.167041
thyroxine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.218192,13.218192,13.218192,17.234619,13.218192,19.428652,13.218192,13.218192,13.218192,13.218192

In [13]:
merged_transcriptomics = merged_transcriptomics[sample_annot_tpm.RNAID]
merged_transcriptomics

,RCC483,RCC486,RCC495,RCC539,RCC540,RCC542,RCC547,RCC560,RCC564,RCC575,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
A1BG,1.304026,1.928762,0.869958,1.880487,1.660118,0.892479,3.436963,2.064896,1.094232,1.749509,...,0.785316,0.977454,0.447450,0.441843,0.662409,0.707219,1.137666,1.488923,1.871112,0.455020
A2M,320.190822,599.699496,759.630310,530.494017,1391.019172,609.172144,53.390407,1413.895848,397.963961,628.208954,...,210.888701,47.498667,76.943934,82.257362,20.723809,20.692371,7.208059,29.921821,21.872767,18.733246
A2MP1,4.301926,1.251719,1.620558,1.792046,1.391611,1.381162,0.117595,3.033230,0.000000,0.914209,...,0.140536,0.052223,0.064615,0.182036,0.360108,0.106965,0.230259,0.361582,0.542156,0.085702
NAT1,8.314472,10.039836,5.763073,8.030295,4.538719,6.406598,3.772830,5.862423,6.280781,7.421067,...,0.211574,0.092810,0.157897,0.179032,0.039136,0.025922,0.033360,0.028881,0.071372,0.032459
NAT2,0.964676,3.234161,0.369455,0.605261,0.396575,0.139946,0.000000,0.240528,0.000000,0.347369,...,0.071581,0.014564,0.105301,0.100544,0.036846,0.009220,0.011865,0.057782,0.019039,0.026642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MAFIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TP53TG3B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SNAR-A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIR4509-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTY8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
sample_annot_tpm_to_metabolomic = {}
for i in sample_annot_tpm.RNAID:
  metabid = sample_annot_tpm[sample_annot_tpm['RNAID'] == i].MetabID.values[0]
  sample_annot_tpm_to_metabolomic[i] = metabid
len(sample_annot_tpm_to_metabolomic)

443

In [15]:
merged_transcriptomics.columns = [sample_annot_tpm_to_metabolomic[i] for i in merged_transcriptomics.columns]
merged_transcriptomics

,MSKC-00397,MSKC-00399,MSKC-00400,MSKC-00404,MSKC-00405,MSKC-00406,MSKC-00407,MSKC-00412,MSKC-00441,MSKC-00417,...,C3N-03183,C3N-03184,C3N-03186,C3N-03188,PT-NPJ7,PT-P44H,PT-R55F,PT-RN5K,PT-UTHO,PT-WVLH
A1BG,1.304026,1.928762,0.869958,1.880487,1.660118,0.892479,3.436963,2.064896,1.094232,1.749509,...,0.785316,0.977454,0.447450,0.441843,0.662409,0.707219,1.137666,1.488923,1.871112,0.455020
A2M,320.190822,599.699496,759.630310,530.494017,1391.019172,609.172144,53.390407,1413.895848,397.963961,628.208954,...,210.888701,47.498667,76.943934,82.257362,20.723809,20.692371,7.208059,29.921821,21.872767,18.733246
A2MP1,4.301926,1.251719,1.620558,1.792046,1.391611,1.381162,0.117595,3.033230,0.000000,0.914209,...,0.140536,0.052223,0.064615,0.182036,0.360108,0.106965,0.230259,0.361582,0.542156,0.085702
NAT1,8.314472,10.039836,5.763073,8.030295,4.538719,6.406598,3.772830,5.862423,6.280781,7.421067,...,0.211574,0.092810,0.157897,0.179032,0.039136,0.025922,0.033360,0.028881,0.071372,0.032459
NAT2,0.964676,3.234161,0.369455,0.605261,0.396575,0.139946,0.000000,0.240528,0.000000,0.347369,...,0.071581,0.014564,0.105301,0.100544,0.036846,0.009220,0.011865,0.057782,0.019039,0.026642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MAFIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TP53TG3B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SNAR-A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIR4509-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTY8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
common_samples = []
for i in merged_metabolomics.columns:
  if i in merged_transcriptomics.columns:
    common_samples.append(i)
  else:
    pass
len(common_samples)

443

In [17]:
merged_transcriptomics_common =  merged_transcriptomics[common_samples]
merged_transcriptomics_common

,DUKE-00651,DUKE-00652,DUKE-00653,DUKE-00654,DUKE-00657,DUKE-00658,DUKE-00660,DUKE-00662,DUKE-00665,DUKE-00666,...,MSKC-00475,MSKC-00477,MSKC-00478,MSKC-00479,MSKC-00481,MSKC-00483,MSKC-00484,MSKC-00485,MSKC-00486,MSKC-00487
A1BG,8.419442,5.732535,10.671391,5.782269,10.816996,8.437941,2.229589,9.797888,8.562957,5.282478,...,7.427487,1.967319,1.995799,3.535053,1.187076,0.966506,0.735974,3.286286,4.350391,2.737016
A2M,176.202102,179.717662,101.369695,137.234012,441.394275,212.912098,61.905951,1000.421531,335.996796,174.347198,...,261.289367,127.091013,108.932315,417.101703,709.773142,228.602987,319.821165,454.219511,194.464475,342.781750
A2MP1,0.056236,0.026734,0.033223,0.168227,0.402998,0.034294,0.407776,1.071284,0.081222,0.139467,...,0.341160,0.204543,0.156355,0.817460,0.784001,0.335248,0.264402,0.960635,0.000000,0.502867
NAT1,144.514353,57.145670,356.324843,14.810037,72.763636,613.714462,2.075390,150.571720,38.742698,1.919218,...,2.390217,0.889484,3.783448,1.658928,1.678447,0.410365,4.718396,3.888043,5.120927,6.058222
NAT2,0.564116,0.950776,0.454457,0.230115,1.102507,0.781841,0.867673,2.442315,0.074068,0.254366,...,0.000000,0.000000,0.285167,0.000000,0.109992,0.000000,0.120557,0.154592,0.043614,0.191073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MAFIP,2.645171,2.364895,2.599040,3.047131,4.835349,4.097796,4.811923,2.494918,0.402147,0.174935,...,6.193569,9.933237,17.537017,1.905661,8.539870,8.659075,4.101876,3.338743,6.977662,8.001949
TP53TG3B,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SNAR-A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIR4509-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TTTY8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
merged_metabolomics_common =  merged_metabolomics[common_samples]
merged_metabolomics_common

,DUKE-00651,DUKE-00652,DUKE-00653,DUKE-00654,DUKE-00657,DUKE-00658,DUKE-00660,DUKE-00662,DUKE-00665,DUKE-00666,...,MSKC-00475,MSKC-00477,MSKC-00478,MSKC-00479,MSKC-00481,MSKC-00483,MSKC-00484,MSKC-00485,MSKC-00486,MSKC-00487
"1,2-propanediol",21.037723,23.959087,20.682481,19.963768,19.677653,24.311710,18.589989,22.315184,20.348804,20.526428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"1,5-anhydroglucitol (1,5-AG)",19.394321,19.044231,19.193116,19.653941,20.145794,19.355534,20.166719,17.094811,18.870517,19.448799,...,20.319000,19.885399,21.351561,20.715546,19.307590,20.623605,19.709740,19.393769,18.795282,19.959657
1-arachidonoyl-GPC (20:4n6),17.671134,14.631118,15.608743,15.383235,17.854153,16.278081,15.690414,17.576460,17.918758,16.385377,...,17.954038,17.954038,18.355977,21.036781,20.517873,20.772511,21.012143,20.316594,19.099814,17.954038
1-arachidonoyl-GPE (20:4n6),14.233610,16.423374,14.400485,15.369813,14.785590,15.876500,14.356789,14.283349,15.348624,15.061306,...,21.292481,21.030432,20.253019,21.416763,21.181656,22.201466,21.916148,20.322285,21.605296,20.333836
1-arachidonoyl-GPI (20:4),14.384728,16.305192,15.299840,14.913759,14.445883,15.213580,14.673009,14.101406,17.416731,15.873187,...,21.842158,20.990560,18.593848,21.243193,21.498352,23.203913,21.409801,20.074359,22.077745,18.603586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nicotinate ribonucleoside,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.876410,15.876410,15.876410,15.876410,15.876410,15.876410,15.876410,18.547371,15.876410,15.876410
norfluoxetine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796,21.917796
palmitoleoyl ethanolamide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.939899,13.940225,13.940225,13.940225,15.396357,14.204030,14.081109,13.940225,13.940225,13.940225
succinimide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.995929,15.167041,15.167041,17.415214,15.167041,16.028156,15.167041,16.306077,20.522298,15.167041
thyroxine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.218192,13.218192,18.139089,13.218192,13.218192,13.218192,13.218192,13.218192,13.218192,16.566960

In [19]:
merged_transcriptomics_common.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/transcriptomics_tpm.csv', index = True)

In [20]:
merged_metabolomics_common.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/metabolomics_log2.csv', index = True)

In [21]:
met_genes = pd.read_csv('drive/My Drive/Colab Notebooks/GP_lab_data/FBA_metabolic_atlas_models/human_gem_associated_genes.csv')
met_genes

              gene_id   Symbol
0     ENSG00000198712   MT-CO2
1     ENSG00000198804   MT-CO1
2     ENSG00000198938   MT-CO3
3     ENSG00000198899  MT-ATP6
4     ENSG00000198886   MT-ND4
...               ...      ...
2879  ENSG00000167751     KLK2
2880  ENSG00000129873    CDY2B
2881  ENSG00000182415    CDY2A
2882  ENSG00000172352    CDY1B
2883  ENSG00000172288     CDY1

[2884 rows x 2 columns]

In [22]:
tpm_met = merged_transcriptomics_common[merged_transcriptomics_common.index.isin(met_genes['Symbol'])]
tpm_met

,DUKE-00651,DUKE-00652,DUKE-00653,DUKE-00654,DUKE-00657,DUKE-00658,DUKE-00660,DUKE-00662,DUKE-00665,DUKE-00666,...,MSKC-00475,MSKC-00477,MSKC-00478,MSKC-00479,MSKC-00481,MSKC-00483,MSKC-00484,MSKC-00485,MSKC-00486,MSKC-00487
NAT1,144.514353,57.145670,356.324843,14.810037,72.763636,613.714462,2.075390,150.571720,38.742698,1.919218,...,2.390217,0.889484,3.783448,1.658928,1.678447,0.410365,4.718396,3.888043,5.120927,6.058222
NAT2,0.564116,0.950776,0.454457,0.230115,1.102507,0.781841,0.867673,2.442315,0.074068,0.254366,...,0.000000,0.000000,0.285167,0.000000,0.109992,0.000000,0.120557,0.154592,0.043614,0.191073
SERPINA3,1879.323517,169.911831,2776.507016,849.949951,345.895191,534.209888,343.133895,210.240127,44.801703,23.951463,...,1.826596,9.795871,1.666364,70.045160,11.817361,5.276481,101.271206,39.393162,2.580822,8.211433
AADAC,2.607398,0.039984,0.248451,0.000000,0.452055,0.076938,0.000000,0.000000,0.121479,0.020859,...,0.000000,0.038240,0.491087,0.000000,0.000000,0.083569,0.000000,0.000000,0.000000,0.219365
AANAT,0.000000,0.074702,0.000000,0.094016,0.090088,0.057498,0.227892,0.099784,0.045392,0.374128,...,0.071498,0.457246,0.454383,1.313442,0.337039,0.499622,0.197020,0.157901,0.026728,0.538649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AK6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TREX1,0.202337,0.028856,0.083676,0.166451,0.057999,0.148067,0.097811,0.128481,0.058447,0.110396,...,0.107404,0.864725,0.067507,0.827210,0.195287,0.261346,0.015855,0.121988,0.017208,0.196007
PGAM2,7.486934,10.340171,62.063505,80.097260,13.497796,9.323630,9.143326,13.928703,5.748129,7.231635,...,27.610344,13.973992,35.496776,22.768575,17.579190,23.960666,21.676149,20.510265,7.171550,33.709000
CEMP1,5.210511,5.140856,5.866129,13.270873,6.234940,5.155916,1.544544,6.138613,8.874405,6.241642,...,10.101671,29.857706,9.840122,13.129559,7.116450,15.775171,4.930365,8.791958,5.769025,8.974167
CDY2A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
tpm_met.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/transcriptomics_tpm_metabolism_related_genes.csv', index = True)

In [24]:
merged_transcriptomics.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/transcriptomics_tpm_benedetti.csv', index = True)

In [25]:
tpm_met_ensembl_id = merged_transcriptomics_common.T.reindex(met_genes['Symbol'], axis = 'columns')
tpm_met_ensembl_id.columns.name = None
tpm_met_ensembl_id

,MT-CO2,MT-CO1,MT-CO3,MT-ATP6,MT-ND4,MT-ND4L,MT-ND2,MT-ND3,EEF1A1,MT-ND1,...,HS3ST4,COX6A2,ENPP7,TGM6,CYP2A13,KLK2,CDY2B,CDY2A,CDY1B,CDY1
DUKE-00651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2312.188455,NaN,...,0.042173,1.535001,0.000000,0.0,0.038375,0.060810,NaN,NaN,NaN,NaN
DUKE-00652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1854.414094,NaN,...,0.000000,0.437822,0.000000,0.0,0.036485,0.298714,NaN,NaN,NaN,NaN
DUKE-00653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2521.493046,NaN,...,0.000000,0.906848,0.064986,0.0,0.022671,0.431106,NaN,NaN,NaN,NaN
DUKE-00654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3615.962913,NaN,...,0.000000,243.252497,0.000000,0.0,0.000000,0.000000,NaN,NaN,NaN,NaN
DUKE-00657,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4045.896211,NaN,...,0.120887,0.330000,0.026276,0.0,0.000000,0.145258,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MSKC-00483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3727.663034,NaN,...,0.000000,0.305025,0.000000,0.0,0.038128,60.821936,NaN,NaN,NaN,NaN
MSKC-00484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4620.661214,NaN,...,0.016523,0.120283,0.086196,0.0,0.000000,4.971588,NaN,NaN,NaN,NaN
MSKC-00485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2403.462293,NaN,...,0.127130,0.154241,0.257906,0.0,0.000000,7.760189,NaN,NaN,NaN,NaN
MSKC-00486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5986.593041,NaN,...,0.000000,0.000000,0.000000,0.0,0.000000,2.861628,NaN,NaN,NaN,NaN
MSKC-00487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4901.620983,NaN,...,0.078565,0.228766,0.000000,0.0,0.000000,5.256408,NaN,NaN,NaN,NaN

In [26]:
met_genes_dict = dict(zip(met_genes['Symbol'], met_genes['gene_id']))
len(met_genes_dict) == len(met_genes)

True

In [27]:
tpm_met_ensembl_id = tpm_met_ensembl_id.rename(columns = met_genes_dict).T
tpm_met_ensembl_id.index.name = None
tpm_met_ensembl_id = tpm_met_ensembl_id.dropna(how = 'all', axis = 'index')
tpm_met_ensembl_id

,DUKE-00651,DUKE-00652,DUKE-00653,DUKE-00654,DUKE-00657,DUKE-00658,DUKE-00660,DUKE-00662,DUKE-00665,DUKE-00666,...,MSKC-00475,MSKC-00477,MSKC-00478,MSKC-00479,MSKC-00481,MSKC-00483,MSKC-00484,MSKC-00485,MSKC-00486,MSKC-00487
ENSG00000198712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000198804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000198938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000198899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENSG00000198886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000182156,0.000000,0.000000,0.064986,0.0,0.026276,0.044720,0.132937,0.000000,0.026479,0.000000,...,0.027805,0.000000,0.000000,0.000000,0.000000,0.000000,0.086196,0.257906,0.000000,0.000000
ENSG00000166948,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.016386,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSG00000197838,0.038375,0.036485,0.022671,0.0,0.000000,0.046804,0.000000,0.000000,0.055425,0.019034,...,0.000000,0.000000,0.000000,0.069728,0.000000,0.038128,0.000000,0.000000,0.000000,0.000000
ENSG00000167751,0.060810,0.298714,0.431106,0.0,0.145258,0.160695,0.000000,0.021452,0.131742,0.291567,...,1.014494,26.043771,13.897696,36.628518,5.456135,60.821936,4.971588,7.760189,2.861628,5.256408
ENSG00000182415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
tpm_met_ensembl_id.to_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/transcriptomics_tpm_metabolism_related_genes_ensembl_id.csv', index = True)