#Import modules

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

#Insert file paths here

In [ ]:
models_path = 'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res'
output_path = 'drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Cell_Reports_revisions_res'

#Load data

In [ ]:
breast_tpm_meta = pd.read_csv('drive/My Drive/Colab Notebooks/Data sets/CPTAC/CPTAC_breast_tpm_meta.csv', index_col = 0)
breast_tpm_meta

,PIK3CA_mutation,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,...,ENSG00000288661,ENSG00000288662,ENSG00000288663,ENSG00000288665,ENSG00000288667,ENSG00000288669,ENSG00000288670,ENSG00000288671,ENSG00000288674,ENSG00000288675
604,0,46.214931,0.073673,209.568850,1.815844,4.408489,7.271645,0.000000,68.825410,4.770622,...,0.0,0.0,0.298338,0.0,0.0,0.000000,14.686817,0.0,0.014689,0.989628
01BR044,1,67.968994,0.416966,208.455711,0.642510,1.712270,10.612816,95.880022,87.821217,11.162665,...,0.0,0.0,0.399698,0.0,0.0,0.000000,3.761095,0.0,0.002352,3.334627
01BR001,0,43.627054,0.522056,68.289461,1.822973,1.946178,2.217605,0.000000,41.608825,7.716013,...,0.0,0.0,0.157181,0.0,0.0,0.000000,4.827286,0.0,0.009408,0.566735
01BR008,0,22.789467,0.167984,110.080881,3.754490,5.663237,10.063559,0.000000,56.689300,7.729134,...,0.0,0.0,0.285136,0.0,0.0,0.021661,7.176883,0.0,0.017706,1.007640
01BR009,0,48.838215,0.228523,148.911739,5.114162,3.567308,12.424822,7.556448,51.864190,10.865596,...,0.0,0.0,0.319950,0.0,0.0,0.028218,9.258385,0.0,0.007322,1.656858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21BR001,0,16.568588,0.084810,85.186175,3.521775,0.494463,6.485950,0.000000,92.902774,5.926566,...,0.0,0.0,0.391365,0.0,0.0,0.000000,3.960743,0.0,0.025028,1.438560
21BR002,1,25.583068,0.000000,92.210946,4.816532,2.040237,14.293264,0.000000,84.501076,9.892575,...,0.0,0.0,0.552384,0.0,0.0,0.000000,4.447699,0.0,0.017618,1.871241
21BR010,1,57.646516,0.817385,145.954725,15.381040,6.117237,2.117512,24.443028,80.056257,44.137923,...,0.0,0.0,0.385925,0.0,0.0,0.000000,28.110244,0.0,0.041093,0.685478
22BR005,1,41.643482,0.938103,158.970625,9.990533,5.291344,6.096627,0.000000,88.365039,33.092256,...,0.0,0.0,0.434093,0.0,0.0,0.000000,14.297169,0.0,0.026937,0.599920
22BR006,1,60.669520,4.870257,112.031846,15.516572,3.549691,5.612526,0.000000,66.798920,12.105413,...,0.0,0.0,0.457949,0.0,0.0,0.000000,11.217921,0.0,0.047217,2.546793

In [ ]:
rna = breast_tpm_meta.copy()
rna = rna.drop(columns = ['PIK3CA_mutation'])
rna

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000288661,ENSG00000288662,ENSG00000288663,ENSG00000288665,ENSG00000288667,ENSG00000288669,ENSG00000288670,ENSG00000288671,ENSG00000288674,ENSG00000288675
604,46.214931,0.073673,209.568850,1.815844,4.408489,7.271645,0.000000,68.825410,4.770622,30.627357,...,0.0,0.0,0.298338,0.0,0.0,0.000000,14.686817,0.0,0.014689,0.989628
01BR044,67.968994,0.416966,208.455711,0.642510,1.712270,10.612816,95.880022,87.821217,11.162665,21.638451,...,0.0,0.0,0.399698,0.0,0.0,0.000000,3.761095,0.0,0.002352,3.334627
01BR001,43.627054,0.522056,68.289461,1.822973,1.946178,2.217605,0.000000,41.608825,7.716013,21.423095,...,0.0,0.0,0.157181,0.0,0.0,0.000000,4.827286,0.0,0.009408,0.566735
01BR008,22.789467,0.167984,110.080881,3.754490,5.663237,10.063559,0.000000,56.689300,7.729134,26.670078,...,0.0,0.0,0.285136,0.0,0.0,0.021661,7.176883,0.0,0.017706,1.007640
01BR009,48.838215,0.228523,148.911739,5.114162,3.567308,12.424822,7.556448,51.864190,10.865596,26.246572,...,0.0,0.0,0.319950,0.0,0.0,0.028218,9.258385,0.0,0.007322,1.656858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21BR001,16.568588,0.084810,85.186175,3.521775,0.494463,6.485950,0.000000,92.902774,5.926566,25.117098,...,0.0,0.0,0.391365,0.0,0.0,0.000000,3.960743,0.0,0.025028,1.438560
21BR002,25.583068,0.000000,92.210946,4.816532,2.040237,14.293264,0.000000,84.501076,9.892575,17.692965,...,0.0,0.0,0.552384,0.0,0.0,0.000000,4.447699,0.0,0.017618,1.871241
21BR010,57.646516,0.817385,145.954725,15.381040,6.117237,2.117512,24.443028,80.056257,44.137923,68.720166,...,0.0,0.0,0.385925,0.0,0.0,0.000000,28.110244,0.0,0.041093,0.685478
22BR005,41.643482,0.938103,158.970625,9.990533,5.291344,6.096627,0.000000,88.365039,33.092256,75.100462,...,0.0,0.0,0.434093,0.0,0.0,0.000000,14.297169,0.0,0.026937,0.599920
22BR006,60.669520,4.870257,112.031846,15.516572,3.549691,5.612526,0.000000,66.798920,12.105413,45.264852,...,0.0,0.0,0.457949,0.0,0.0,0.000000,11.217921,0.0,0.047217,2.546793

In [ ]:
rna.index.name = None
rna = rna.fillna(0)
rna

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000288661,ENSG00000288662,ENSG00000288663,ENSG00000288665,ENSG00000288667,ENSG00000288669,ENSG00000288670,ENSG00000288671,ENSG00000288674,ENSG00000288675
604,46.214931,0.073673,209.568850,1.815844,4.408489,7.271645,0.000000,68.825410,4.770622,30.627357,...,0.0,0.0,0.298338,0.0,0.0,0.000000,14.686817,0.0,0.014689,0.989628
01BR044,67.968994,0.416966,208.455711,0.642510,1.712270,10.612816,95.880022,87.821217,11.162665,21.638451,...,0.0,0.0,0.399698,0.0,0.0,0.000000,3.761095,0.0,0.002352,3.334627
01BR001,43.627054,0.522056,68.289461,1.822973,1.946178,2.217605,0.000000,41.608825,7.716013,21.423095,...,0.0,0.0,0.157181,0.0,0.0,0.000000,4.827286,0.0,0.009408,0.566735
01BR008,22.789467,0.167984,110.080881,3.754490,5.663237,10.063559,0.000000,56.689300,7.729134,26.670078,...,0.0,0.0,0.285136,0.0,0.0,0.021661,7.176883,0.0,0.017706,1.007640
01BR009,48.838215,0.228523,148.911739,5.114162,3.567308,12.424822,7.556448,51.864190,10.865596,26.246572,...,0.0,0.0,0.319950,0.0,0.0,0.028218,9.258385,0.0,0.007322,1.656858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21BR001,16.568588,0.084810,85.186175,3.521775,0.494463,6.485950,0.000000,92.902774,5.926566,25.117098,...,0.0,0.0,0.391365,0.0,0.0,0.000000,3.960743,0.0,0.025028,1.438560
21BR002,25.583068,0.000000,92.210946,4.816532,2.040237,14.293264,0.000000,84.501076,9.892575,17.692965,...,0.0,0.0,0.552384,0.0,0.0,0.000000,4.447699,0.0,0.017618,1.871241
21BR010,57.646516,0.817385,145.954725,15.381040,6.117237,2.117512,24.443028,80.056257,44.137923,68.720166,...,0.0,0.0,0.385925,0.0,0.0,0.000000,28.110244,0.0,0.041093,0.685478
22BR005,41.643482,0.938103,158.970625,9.990533,5.291344,6.096627,0.000000,88.365039,33.092256,75.100462,...,0.0,0.0,0.434093,0.0,0.0,0.000000,14.297169,0.0,0.026937,0.599920
22BR006,60.669520,4.870257,112.031846,15.516572,3.549691,5.612526,0.000000,66.798920,12.105413,45.264852,...,0.0,0.0,0.457949,0.0,0.0,0.000000,11.217921,0.0,0.047217,2.546793

In [ ]:
rna = rna.apply(lambda x: np.log2(x + 1))
rna.head(3)

,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,ENSG00000001167,...,ENSG00000288661,ENSG00000288662,ENSG00000288663,ENSG00000288665,ENSG00000288667,ENSG00000288669,ENSG00000288670,ENSG00000288671,ENSG00000288674,ENSG00000288675
604,5.561171,0.102554,7.718148,1.493567,2.435225,3.048174,0.000000,6.125680,2.528727,4.983101,...,0.0,0.0,0.376666,0.0,0.0,0.0,3.971481,0.0,0.021037,0.992498
01BR044,6.107876,0.502805,7.710501,0.715902,1.439501,3.537646,6.598127,6.472832,3.604387,4.500703,...,0.0,0.0,0.485116,0.0,0.0,0.0,2.251293,0.0,0.003389,2.115908
01BR001,5.479847,0.606021,6.114564,1.497215,1.558844,1.685987,0.000000,5.413080,3.123668,4.486913,...,0.0,0.0,0.210614,0.0,0.0,0.0,2.542824,0.0,0.013509,0.647761

#Import Ensemble

In [ ]:
#Import elastic net

import joblib

model_1 = joblib.load(f'{models_path}/ElasticNet.pkl')

In [ ]:
ensemble_features = model_1.feature_names_in_
ensemble_features

array(['ENSG00000198712', 'ENSG00000198804', 'ENSG00000198938', ...,
       'ENSG00000197838', 'ENSG00000167751', 'ENSG00000182415'],
      dtype=object)

In [ ]:
import pickle

with open(f'{models_path}/y_train_features.pkl', 'rb') as f:
    ensemble_y_train_features_loaded = pickle.load(f)

print(ensemble_y_train_features_loaded)

Index(['1,5-anhydroglucitol (1,5-AG)', '1-arachidonoyl-GPC (20:4n6)',
       '1-arachidonoyl-GPE (20:4n6)', '1-arachidonoyl-GPI (20:4)',
       '1-linoleoylglycerol (18:2)', '1-linoleoyl-GPC (18:2)',
       '1-oleoylglycerol (1-monoolein)', '1-oleoyl-GPE (18:1)',
       '1-palmitoleoyl-GPC (16:1)', '1-palmitoylglycerol (1-monopalmitin)',
       ...
       'urea', 'uridine', 'valine', 'valylglycine', 'xanthine', 'xanthosine',
       '3-phosphoglycerate', 'dehydroascorbate', 'pyruvate',
       'phosphoenolpyruvate (PEP)'],
      dtype='object', length=218)

In [ ]:
#Import random forest regressor

model_2 = joblib.load(f'{models_path}/Random Forest Regressor.pkl')

In [ ]:
#Import final estimator

final_estimator = joblib.load(f'{models_path}/Ensemble.pkl')

#Import NN

In [ ]:
import joblib
import tensorflow as tf

In [ ]:
var_model = tf.keras.models.load_model('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/models/Transfer_metabolomics_unbiased_features_nn_model.keras')

In [ ]:
var_model.summary()

Model: "functional_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 3030)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │     3,103,744 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 512)            │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ new_output_dense (Dense)        │ (None, 218)            │        56,026 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,935,120 (15.01 MB)

 Trainable params: 56,026 (218.85 KB)

 Non-trainable params: 3,767,040 (14.37 MB)

 Optimizer params: 112,054 (437.71 KB)

In [ ]:
with open('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/models/Transfer_metabolomics_unbiased_features_nn_model_features_input.pkl', 'rb') as f:
  var_model_input_features = pickle.load(f)

print(var_model_input_features)

['ENSG00000000005', 'ENSG00000000419', 'ENSG00000000971', 'ENSG00000001617', 'ENSG00000002549', 'ENSG00000002586', 'ENSG00000002726', 'ENSG00000002834', 'ENSG00000002933', 'ENSG00000003989', 'ENSG00000004059', 'ENSG00000004142', 'ENSG00000004478', 'ENSG00000004776', 'ENSG00000004779', 'ENSG00000004799', 'ENSG00000004939', 'ENSG00000005022', 'ENSG00000005075', 'ENSG00000005421', 'ENSG00000005486', 'ENSG00000005513', 'ENSG00000005884', 'ENSG00000006016', 'ENSG00000006125', 'ENSG00000006128', 'ENSG00000006210', 'ENSG00000006327', 'ENSG00000006659', 'ENSG00000006831', 'ENSG00000007080', 'ENSG00000007255', 'ENSG00000007306', 'ENSG00000007312', 'ENSG00000007350', 'ENSG00000007933', 'ENSG00000007952', 'ENSG00000008018', 'ENSG00000008282', 'ENSG00000008283', 'ENSG00000008394', 'ENSG00000008441', 'ENSG00000008517', 'ENSG00000008988', 'ENSG00000009307', 'ENSG00000009765', 'ENSG00000010256', 'ENSG00000010278', 'ENSG00000010438', 'ENSG00000010610', 'ENSG00000011009', 'ENSG00000011028', 'ENSG00000011304', 'ENSG00000011465', 'ENSG00000011600', 'ENSG00000012223', 'ENSG00000012660', 'ENSG00000013275', 'ENSG00000013306', 'ENSG00000013364', 'ENSG00000013583', 'ENSG00000013588', 'ENSG00000014216', 'ENSG00000014257', 'ENSG00000015413', 'ENSG00000016490', 'ENSG00000016602', 'ENSG00000018236', 'ENSG00000018625', 'ENSG00000019102', 'ENSG00000019169', 'ENSG00000019186', 'ENSG00000019582', 'ENSG00000021300', 'ENSG00000021355', 'ENSG00000021826', 'ENSG00000021852', 'ENSG00000022267', 'ENSG00000023330', 'ENSG00000023734', 'ENSG00000024422', 'ENSG00000025423', 'ENSG00000025708', 'ENSG00000025772', 'ENSG00000026025', 'ENSG00000026508', 'ENSG00000027697', 'ENSG00000029559', 'ENSG00000029993', 'ENSG00000030582', 'ENSG00000034510', 'ENSG00000034713', 'ENSG00000034971', 'ENSG00000035862', 'ENSG00000036565', 'ENSG00000038427', 'ENSG00000039068', 'ENSG00000041982', 'ENSG00000042493', 'ENSG00000042753', 'ENSG00000042832', 'ENSG00000044115', 'ENSG00000044574', 'ENSG00000046604', 'ENSG00000046653', 'ENSG00000047457', 'ENSG00000049089', 'ENSG00000049245', 'ENSG00000049323', 'ENSG00000049540', 'ENSG00000050405', 'ENSG00000050767', 'ENSG00000051108', 'ENSG00000051523', 'ENSG00000052344', 'ENSG00000052802', 'ENSG00000053438', 'ENSG00000053747', 'ENSG00000054148', 'ENSG00000054793', 'ENSG00000054938', 'ENSG00000055957', 'ENSG00000057149', 'ENSG00000057608', 'ENSG00000057757', 'ENSG00000058085', 'ENSG00000058262', 'ENSG00000058668', 'ENSG00000059573', 'ENSG00000059804', 'ENSG00000060138', 'ENSG00000060566', 'ENSG00000060718', 'ENSG00000060762', 'ENSG00000060982', 'ENSG00000061794', 'ENSG00000062038', 'ENSG00000062716', 'ENSG00000063046', 'ENSG00000063177', 'ENSG00000063180', 'ENSG00000063244', 'ENSG00000063660', 'ENSG00000064300', 'ENSG00000064651', 'ENSG00000064655', 'ENSG00000064666', 'ENSG00000064886', 'ENSG00000065054', 'ENSG00000065154', 'ENSG00000065361', 'ENSG00000065518', 'ENSG00000065534', 'ENSG00000065618', 'ENSG00000065978', 'ENSG00000066322', 'ENSG00000066405', 'ENSG00000066583', 'ENSG00000067057', 'ENSG00000067082', 'ENSG00000067113', 'ENSG00000067167', 'ENSG00000067182', 'ENSG00000067225', 'ENSG00000067560', 'ENSG00000067704', 'ENSG00000067715', 'ENSG00000067840', 'ENSG00000068078', 'ENSG00000068079', 'ENSG00000068697', 'ENSG00000068912', 'ENSG00000068976', 'ENSG00000069011', 'ENSG00000069122', 'ENSG00000069275', 'ENSG00000069399', 'ENSG00000069482', 'ENSG00000069535', 'ENSG00000069849', 'ENSG00000070087', 'ENSG00000070404', 'ENSG00000070413', 'ENSG00000070526', 'ENSG00000070756', 'ENSG00000071082', 'ENSG00000071127', 'ENSG00000071203', 'ENSG00000071553', 'ENSG00000071575', 'ENSG00000071859', 'ENSG00000071967', 'ENSG00000072042', 'ENSG00000072080', 'ENSG00000072110', 'ENSG00000072274', 'ENSG00000072310', 'ENSG00000072506', 'ENSG00000072778', 'ENSG00000073060', 'ENSG00000073067', 'ENSG00000073282', 'ENSG00000073756', 'ENSG00000073849', 'ENSG00000074071', 'ENSG00000074181', 'ENSG00000074370', 'ENSG00000074410', 'ENSG00000074527', 'ENSG00000074695', 'ENSG00000074800', 'ENSG00000074803', 'ENSG00000074842', 'ENSG00000075142', 'ENSG00000075223', 'ENSG00000075426', 'ENSG00000075461', 'ENSG00000075618', 'ENSG00000075624', 'ENSG00000075785', 'ENSG00000076706', 'ENSG00000076716', 'ENSG00000076864', 'ENSG00000077009', 'ENSG00000077097', 'ENSG00000077147', 'ENSG00000077274', 'ENSG00000077498', 'ENSG00000077522', 'ENSG00000077942', 'ENSG00000078018', 'ENSG00000078081', 'ENSG00000078369', 'ENSG00000078549', 'ENSG00000078596', 'ENSG00000078668', 'ENSG00000078898', 'ENSG00000079112', 'ENSG00000079215', 'ENSG00000079246', 'ENSG00000079308', 'ENSG00000079459', 'ENSG00000079462', 'ENSG00000079557', 'ENSG00000079689', 'ENSG00000080166', 'ENSG00000080493', 'ENSG00000080644', 'ENSG00000080824', 'ENSG00000080910', 'ENSG00000081041', 'ENSG00000081051', 'ENSG00000081154', 'ENSG00000081277', 'ENSG00000082641', 'ENSG00000082781', 'ENSG00000083444', 'ENSG00000083720', 'ENSG00000083845', 'ENSG00000084090', 'ENSG00000084207', 'ENSG00000084234', 'ENSG00000084674', 'ENSG00000084733', 'ENSG00000084754', 'ENSG00000085063', 'ENSG00000085117', 'ENSG00000085465', 'ENSG00000085662', 'ENSG00000085733', 'ENSG00000086061', 'ENSG00000086062', 'ENSG00000086065', 'ENSG00000086205', 'ENSG00000086548', 'ENSG00000086598', 'ENSG00000087074', 'ENSG00000087076', 'ENSG00000087077', 'ENSG00000087086', 'ENSG00000087128', 'ENSG00000087245', 'ENSG00000087250', 'ENSG00000087460', 'ENSG00000087494', 'ENSG00000088247', 'ENSG00000088305', 'ENSG00000088325', 'ENSG00000088832', 'ENSG00000088882', 'ENSG00000088986', 'ENSG00000088992', 'ENSG00000089009', 'ENSG00000089063', 'ENSG00000089157', 'ENSG00000089199', 'ENSG00000089220', 'ENSG00000089248', 'ENSG00000089280', 'ENSG00000089289', 'ENSG00000089327', 'ENSG00000089597', 'ENSG00000089693', 'ENSG00000090006', 'ENSG00000090013', 'ENSG00000090104', 'ENSG00000090273', 'ENSG00000090339', 'ENSG00000090382', 'ENSG00000090776', 'ENSG00000090932', 'ENSG00000091129', 'ENSG00000091137', 'ENSG00000091138', 'ENSG00000091317', 'ENSG00000091409', 'ENSG00000091483', 'ENSG00000091513', 'ENSG00000091527', 'ENSG00000091583', 'ENSG00000091704', 'ENSG00000091831', 'ENSG00000091947', 'ENSG00000091986', 'ENSG00000092010', 'ENSG00000092054', 'ENSG00000092068', 'ENSG00000092096', 'ENSG00000092199', 'ENSG00000092295', 'ENSG00000092621', 'ENSG00000092758', 'ENSG00000092820', 'ENSG00000092841', 'ENSG00000092964', 'ENSG00000094755', 'ENSG00000094796', 'ENSG00000095139', 'ENSG00000095303', 'ENSG00000095321', 'ENSG00000095713', 'ENSG00000095739', 'ENSG00000095932', 'ENSG00000095970', 'ENSG00000096006', 'ENSG00000096088', 'ENSG00000096092', 'ENSG00000096384', 'ENSG00000096696', 'ENSG00000099194', 'ENSG00000099282', 'ENSG00000099341', 'ENSG00000099622', 'ENSG00000099624', 'ENSG00000099783', 'ENSG00000099795', 'ENSG00000099800', 'ENSG00000099812', 'ENSG00000099834', 'ENSG00000099849', 'ENSG00000099860', 'ENSG00000099875', 'ENSG00000099937', 'ENSG00000099953', 'ENSG00000099994', 'ENSG00000100075', 'ENSG00000100079', 'ENSG00000100095', 'ENSG00000100097', 'ENSG00000100129', 'ENSG00000100138', 'ENSG00000100146', 'ENSG00000100196', 'ENSG00000100197', 'ENSG00000100201', 'ENSG00000100216', 'ENSG00000100219', 'ENSG00000100234', 'ENSG00000100243', 'ENSG00000100253', 'ENSG00000100285', 'ENSG00000100292', 'ENSG00000100300', 'ENSG00000100304', 'ENSG00000100316', 'ENSG00000100342', 'ENSG00000100345', 'ENSG00000100348', 'ENSG00000100353', 'ENSG00000100362', 'ENSG00000100373', 'ENSG00000100380', 'ENSG00000100427', 'ENSG00000100448', 'ENSG00000100504', 'ENSG00000100558', 'ENSG00000100591', 'ENSG00000100600', 'ENSG00000100604', 'ENSG00000100612', 'ENSG00000100632', 'ENSG00000100644', 'ENSG00000100650', 'ENSG00000100652', 'ENSG00000100665', 'ENSG00000100804', 'ENSG00000100823', 'ENSG00000100867', 'ENSG00000100889', 'ENSG00000100906', 'ENSG00000100911', 'ENSG00000100979', 'ENSG00000100985', 'ENSG00000100991', 'ENSG00000100994', 'ENSG00000101000', 'ENSG00000101057', 'ENSG00000101160', 'ENSG00000101161', 'ENSG00000101166', 'ENSG00000101182', 'ENSG00000101197', 'ENSG00000101198', 'ENSG00000101210', 'ENSG00000101220', 'ENSG00000101224', 'ENSG00000101255', 'ENSG00000101265', 'ENSG00000101311', 'ENSG00000101323', 'ENSG00000101335', 'ENSG00000101367', 'ENSG00000101384', 'ENSG00000101400', 'ENSG00000101421', 'ENSG00000101439', 'ENSG00000101441', 'ENSG00000101443', 'ENSG00000101444', 'ENSG00000101457', 'ENSG00000101470', 'ENSG00000101474', 'ENSG00000101608', 'ENSG00000101825', 'ENSG00000101842', 'ENSG00000101850', 'ENSG00000101856', 'ENSG00000101911', 'ENSG00000101938', 'ENSG00000101955', 'ENSG00000102003', 'ENSG00000102007', 'ENSG00000102024', 'ENSG00000102054', 'ENSG00000102096', 'ENSG00000102109', 'ENSG00000102144', 'ENSG00000102172', 'ENSG00000102226', 'ENSG00000102241', 'ENSG00000102243', 'ENSG00000102265', 'ENSG00000102316', 'ENSG00000102317', 'ENSG00000102401', 'ENSG00000102409', 'ENSG00000102554', 'ENSG00000102575', 'ENSG00000102760', 'ENSG00000102804', 'ENSG00000102837', 'ENSG00000102854', 'ENSG00000102879', 'ENSG00000102891', 'ENSG00000102970', 'ENSG00000102996', 'ENSG00000103024', 'ENSG00000103034', 'ENSG00000103044', 'ENSG00000103145', 'ENSG00000103187', 'ENSG00000103202', 'ENSG00000103257', 'ENSG00000103260', 'ENSG00000103363', 'ENSG00000103375', 'ENSG00000103485', 'ENSG00000103569', 'ENSG00000103710', 'ENSG00000103811', 'ENSG00000104112', 'ENSG00000104140', 'ENSG00000104267', 'ENSG00000104324', 'ENSG00000104332', 'ENSG00000104341', 'ENSG00000104368', 'ENSG00000104371', 'ENSG00000104413', 'ENSG00000104419', 'ENSG00000104435', 'ENSG00000104447', 'ENSG00000104522', 'ENSG00000104549', 'ENSG00000104635', 'ENSG00000104687', 'ENSG00000104760', 'ENSG00000104765', 'ENSG00000104783', 'ENSG00000104805', 'ENSG00000104823', 'ENSG00000104833', 'ENSG00000104852', 'ENSG00000104870', 'ENSG00000104879', 'ENSG00000104904', 'ENSG00000104951', 'ENSG00000104964', 'ENSG00000104979', 'ENSG00000105048', 'ENSG00000105088', 'ENSG00000105141', 'ENSG00000105193', 'ENSG00000105202', 'ENSG00000105220', 'ENSG00000105223', 'ENSG00000105251', 'ENSG00000105270', 'ENSG00000105281', 'ENSG00000105290', 'ENSG00000105323', 'ENSG00000105329', 'ENSG00000105357', 'ENSG00000105369', 'ENSG00000105372', 'ENSG00000105373', 'ENSG00000105374', 'ENSG00000105388', 'ENSG00000105398', 'ENSG00000105401', 'ENSG00000105427', 'ENSG00000105438', 'ENSG00000105472', 'ENSG00000105519', 'ENSG00000105568', 'ENSG00000105640', 'ENSG00000105655', 'ENSG00000105664', 'ENSG00000105668', 'ENSG00000105669', 'ENSG00000105675', 'ENSG00000105677', 'ENSG00000105695', 'ENSG00000105696', 'ENSG00000105699', 'ENSG00000105701', 'ENSG00000105707', 'ENSG00000105755', 'ENSG00000105767', 'ENSG00000105825', 'ENSG00000105835', 'ENSG00000105854', 'ENSG00000105880', 'ENSG00000105887', 'ENSG00000105894', 'ENSG00000105929', 'ENSG00000105953', 'ENSG00000105974', 'ENSG00000105976', 'ENSG00000106003', 'ENSG00000106025', 'ENSG00000106049', 'ENSG00000106066', 'ENSG00000106077', 'ENSG00000106153', 'ENSG00000106178', 'ENSG00000106211', 'ENSG00000106236', 'ENSG00000106244', 'ENSG00000106278', 'ENSG00000106327', 'ENSG00000106333', 'ENSG00000106366', 'ENSG00000106367', 'ENSG00000106397', 'ENSG00000106483', 'ENSG00000106484', 'ENSG00000106537', 'ENSG00000106538', 'ENSG00000106541', 'ENSG00000106565', 'ENSG00000106605', 'ENSG00000106624', 'ENSG00000106628', 'ENSG00000106803', 'ENSG00000106809', 'ENSG00000106819', 'ENSG00000106853', 'ENSG00000106927', 'ENSG00000106991', 'ENSG00000107018', 'ENSG00000107159', 'ENSG00000107165', 'ENSG00000107175', 'ENSG00000107223', 'ENSG00000107281', 'ENSG00000107317', 'ENSG00000107438', 'ENSG00000107447', 'ENSG00000107485', 'ENSG00000107537', 'ENSG00000107562', 'ENSG00000107581', 'ENSG00000107742', 'ENSG00000107796', 'ENSG00000107798', 'ENSG00000107833', 'ENSG00000107874', 'ENSG00000107984', 'ENSG00000108107', 'ENSG00000108179', 'ENSG00000108244', 'ENSG00000108298', 'ENSG00000108344', 'ENSG00000108468', 'ENSG00000108515', 'ENSG00000108518', 'ENSG00000108551', 'ENSG00000108561', 'ENSG00000108602', 'ENSG00000108604', 'ENSG00000108639', 'ENSG00000108654', 'ENSG00000108679', 'ENSG00000108691', 'ENSG00000108821', 'ENSG00000108828', 'ENSG00000108829', 'ENSG00000108830', 'ENSG00000108849', 'ENSG00000108946', 'ENSG00000108953', 'ENSG00000109062', 'ENSG00000109063', 'ENSG00000109072', 'ENSG00000109084', 'ENSG00000109107', 'ENSG00000109113', 'ENSG00000109181', 'ENSG00000109205', 'ENSG00000109255', 'ENSG00000109321', 'ENSG00000109436', 'ENSG00000109472', 'ENSG00000109475', 'ENSG00000109511', 'ENSG00000109610', 'ENSG00000109736', 'ENSG00000109814', 'ENSG00000109846', 'ENSG00000109971', 'ENSG00000110042', 'ENSG00000110092', 'ENSG00000110107', 'ENSG00000110108', 'ENSG00000110169', 'ENSG00000110195', 'ENSG00000110243', 'ENSG00000110244', 'ENSG00000110245', 'ENSG00000110321', 'ENSG00000110330', 'ENSG00000110375', 'ENSG00000110400', 'ENSG00000110484', 'ENSG00000110492', 'ENSG00000110651', 'ENSG00000110680', 'ENSG00000110700', 'ENSG00000110711', 'ENSG00000110799', 'ENSG00000110917', 'ENSG00000110955', 'ENSG00000110958', 'ENSG00000111057', 'ENSG00000111229', 'ENSG00000111245', 'ENSG00000111275', 'ENSG00000111276', 'ENSG00000111319', 'ENSG00000111328', 'ENSG00000111331', 'ENSG00000111335', 'ENSG00000111341', 'ENSG00000111348', 'ENSG00000111371', 'ENSG00000111481', 'ENSG00000111639', 'ENSG00000111640', 'ENSG00000111667', 'ENSG00000111669', 'ENSG00000111674', 'ENSG00000111676', 'ENSG00000111726', 'ENSG00000111799', 'ENSG00000111843', 'ENSG00000111897', 'ENSG00000112096', 'ENSG00000112118', 'ENSG00000112299', 'ENSG00000112306', 'ENSG00000112308', 'ENSG00000112335', 'ENSG00000112378', 'ENSG00000112473', 'ENSG00000112514', 'ENSG00000112559', 'ENSG00000112562', 'ENSG00000112667', 'ENSG00000112695', 'ENSG00000112697', 'ENSG00000112715', 'ENSG00000112759', 'ENSG00000112812', 'ENSG00000112818', 'ENSG00000112936', 'ENSG00000112977', 'ENSG00000113070', 'ENSG00000113083', 'ENSG00000113140', 'ENSG00000113296', 'ENSG00000113328', 'ENSG00000113368', 'ENSG00000113369', 'ENSG00000113384', 'ENSG00000113504', 'ENSG00000113583', 'ENSG00000113600', 'ENSG00000113657', 'ENSG00000113719', 'ENSG00000113721', 'ENSG00000113722', 'ENSG00000113732', 'ENSG00000113739', 'ENSG00000113758', 'ENSG00000113889', 'ENSG00000113905', 'ENSG00000113924', 'ENSG00000113946', 'ENSG00000114113', 'ENSG00000114115', 'ENSG00000114200', 'ENSG00000114270', 'ENSG00000114315', 'ENSG00000114353', 'ENSG00000114391', 'ENSG00000114573', 'ENSG00000114631', 'ENSG00000114638', 'ENSG00000114646', 'ENSG00000114686', 'ENSG00000114771', 'ENSG00000114850', 'ENSG00000114854', 'ENSG00000114867', 'ENSG00000114942', 'ENSG00000115009', 'ENSG00000115053', 'ENSG00000115128', 'ENSG00000115221', 'ENSG00000115241', 'ENSG00000115255', 'ENSG00000115263', 'ENSG00000115268', 'ENSG00000115306', 'ENSG00000115307', 'ENSG00000115310', 'ENSG00000115380', 'ENSG00000115386', 'ENSG00000115414', 'ENSG00000115415', 'ENSG00000115457', 'ENSG00000115461', 'ENSG00000115468', 'ENSG00000115484', 'ENSG00000115590', 'ENSG00000115648', 'ENSG00000115677', 'ENSG00000115705', 'ENSG00000115718', 'ENSG00000115738', 'ENSG00000115758', 'ENSG00000115828', 'ENSG00000115884', 'ENSG00000115963', 'ENSG00000116016', 'ENSG00000116030', 'ENSG00000116044', 'ENSG00000116096', 'ENSG00000116133', 'ENSG00000116147', 'ENSG00000116260', 'ENSG00000116285', 'ENSG00000116288', 'ENSG00000116299', 'ENSG00000116459', 'ENSG00000116478', 'ENSG00000116489', 'ENSG00000116521', 'ENSG00000116560', 'ENSG00000116574', 'ENSG00000116586', 'ENSG00000116649', 'ENSG00000116679', 'ENSG00000116690', 'ENSG00000116717', 'ENSG00000116729', 'ENSG00000116741', 'ENSG00000116774', 'ENSG00000116791', 'ENSG00000116824', 'ENSG00000116857', 'ENSG00000116962', 'ENSG00000116990', 'ENSG00000117115', 'ENSG00000117122', 'ENSG00000117143', 'ENSG00000117152', 'ENSG00000117228', 'ENSG00000117298', 'ENSG00000117318', 'ENSG00000117335', 'ENSG00000117362', 'ENSG00000117394', 'ENSG00000117399', 'ENSG00000117410', 'ENSG00000117448', 'ENSG00000117450', 'ENSG00000117472', 'ENSG00000117480', 'ENSG00000117519', 'ENSG00000117525', 'ENSG00000117592', 'ENSG00000117594', 'ENSG00000117595', 'ENSG00000117601', 'ENSG00000117632', 'ENSG00000117691', 'ENSG00000117983', 'ENSG00000117984', 'ENSG00000118137', 'ENSG00000118181', 'ENSG00000118271', 'ENSG00000118418', 'ENSG00000118508', 'ENSG00000118520', 'ENSG00000118523', 'ENSG00000118564', 'ENSG00000118640', 'ENSG00000118680', 'ENSG00000118702', 'ENSG00000118705', 'ENSG00000118785', 'ENSG00000118816', 'ENSG00000118849', 'ENSG00000118898', 'ENSG00000118971', 'ENSG00000119013', 'ENSG00000119147', 'ENSG00000119318', 'ENSG00000119326', 'ENSG00000119333', 'ENSG00000119335', 'ENSG00000119421', 'ENSG00000119632', 'ENSG00000119655', 'ENSG00000119681', 'ENSG00000119888', 'ENSG00000119917', 'ENSG00000120053', 'ENSG00000120057', 'ENSG00000120129', 'ENSG00000120215', 'ENSG00000120306', 'ENSG00000120438', 'ENSG00000120708', 'ENSG00000120738', 'ENSG00000120742', 'ENSG00000120875', 'ENSG00000120885', 'ENSG00000121005', 'ENSG00000121039', 'ENSG00000121064', 'ENSG00000121316', 'ENSG00000121552', 'ENSG00000121653', 'ENSG00000121691', 'ENSG00000121742', 'ENSG00000121769', 'ENSG00000121774', 'ENSG00000121858', 'ENSG00000121900', 'ENSG00000121966', 'ENSG00000122026', 'ENSG00000122034', 'ENSG00000122133', 'ENSG00000122176', 'ENSG00000122180', 'ENSG00000122194', 'ENSG00000122218', 'ENSG00000122359', 'ENSG00000122406', 'ENSG00000122565', 'ENSG00000122566', 'ENSG00000122585', 'ENSG00000122642', 'ENSG00000122679', 'ENSG00000122705', 'ENSG00000122711', 'ENSG00000122786', 'ENSG00000122852', 'ENSG00000122861', 'ENSG00000122862', 'ENSG00000122877', 'ENSG00000122884', 'ENSG00000123091', 'ENSG00000123095', 'ENSG00000123131', 'ENSG00000123143', 'ENSG00000123144', 'ENSG00000123159', 'ENSG00000123358', 'ENSG00000123384', 'ENSG00000123416', 'ENSG00000123454', 'ENSG00000123500', 'ENSG00000123560', 'ENSG00000123561', 'ENSG00000123562', 'ENSG00000123689', 'ENSG00000123838', 'ENSG00000123843', 'ENSG00000123892', 'ENSG00000123975', 'ENSG00000123983', 'ENSG00000123989', 'ENSG00000123999', 'ENSG00000124098', 'ENSG00000124102', 'ENSG00000124107', 'ENSG00000124126', 'ENSG00000124145', 'ENSG00000124157', 'ENSG00000124172', 'ENSG00000124207', 'ENSG00000124212', 'ENSG00000124214', 'ENSG00000124225', 'ENSG00000124233', 'ENSG00000124237', 'ENSG00000124253', 'ENSG00000124422', 'ENSG00000124466', 'ENSG00000124491', 'ENSG00000124562', 'ENSG00000124564', 'ENSG00000124664', 'ENSG00000124702', 'ENSG00000124713', 'ENSG00000124762', 'ENSG00000124766', 'ENSG00000124767', 'ENSG00000124935', 'ENSG00000124939', 'ENSG00000124942', 'ENSG00000125144', 'ENSG00000125148', 'ENSG00000125166', 'ENSG00000125257', 'ENSG00000125304', 'ENSG00000125356', 'ENSG00000125398', 'ENSG00000125414', 'ENSG00000125462', 'ENSG00000125520', 'ENSG00000125534', 'ENSG00000125618', 'ENSG00000125652', 'ENSG00000125691', 'ENSG00000125730', 'ENSG00000125740', 'ENSG00000125743', 'ENSG00000125753', 'ENSG00000125810', 'ENSG00000125813', 'ENSG00000125817', 'ENSG00000125835', 'ENSG00000125844', 'ENSG00000125851', 'ENSG00000125868', 'ENSG00000125869', 'ENSG00000125901', 'ENSG00000125968', 'ENSG00000125977', 'ENSG00000125991', 'ENSG00000125995', 'ENSG00000125999', 'ENSG00000126218', 'ENSG00000126233', 'ENSG00000126247', 'ENSG00000126254', 'ENSG00000126267', 'ENSG00000126337', 'ENSG00000126432', 'ENSG00000126457', 'ENSG00000126458', 'ENSG00000126524', 'ENSG00000126545', 'ENSG00000126549', 'ENSG00000126550', 'ENSG00000126709', 'ENSG00000126756', 'ENSG00000126878', 'ENSG00000126945', 'ENSG00000127022', 'ENSG00000127184', 'ENSG00000127324', 'ENSG00000127418', 'ENSG00000127585', 'ENSG00000127824', 'ENSG00000127831', 'ENSG00000127837', 'ENSG00000127884', 'ENSG00000127920', 'ENSG00000127948', 'ENSG00000128016', 'ENSG00000128185', 'ENSG00000128218', 'ENSG00000128228', 'ENSG00000128245', 'ENSG00000128272', 'ENSG00000128283', 'ENSG00000128311', 'ENSG00000128340', 'ENSG00000128422', 'ENSG00000128524', 'ENSG00000128564', 'ENSG00000128567', 'ENSG00000128591', 'ENSG00000128595', 'ENSG00000129009', 'ENSG00000129103', 'ENSG000001

In [ ]:
len(var_model_input_features)

3030

In [ ]:
with open('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/models/Transfer_metabolomics_unbiased_features_nn_model_features_output.pkl', 'rb') as f:
  var_model_output_features = pickle.load(f)

print(var_model_output_features)

['1,5-anhydroglucitol (1,5-AG)', '1-arachidonoyl-GPC (20:4n6)', '1-arachidonoyl-GPE (20:4n6)', '1-arachidonoyl-GPI (20:4)', '1-linoleoylglycerol (18:2)', '1-linoleoyl-GPC (18:2)', '1-oleoylglycerol (1-monoolein)', '1-oleoyl-GPE (18:1)', '1-palmitoleoyl-GPC (16:1)', '1-palmitoylglycerol (1-monopalmitin)', '1-palmitoyl-GPC (16:0)', '1-palmitoyl-GPE (16:0)', '1-palmitoyl-GPI (16:0)', '1-(1-enyl-palmitoyl)-GPE (P-16:0)', '1-stearoyl-GPC (18:0)', '1-stearoyl-GPI (18:0)', '10-heptadecenoate (17:1n7)', '10-nonadecenoate (19:1n9)', '13-HODE + 9-HODE', 'methyl palmitate (15 or 2)', "2'-deoxyguanosine", "2'-deoxyinosine", '2-aminoadipate', '2-hydroxyglutarate', '2-hydroxypalmitate', '2-methylbutyroylcarnitine', '2-palmitoyl-GPC (16:0)', '3-(4-hydroxyphenyl)lactate', '3-aminoisobutyrate', '3-carboxy-4-methyl-5-propyl-2-furanpropanoate (CMPF)', '3-hydroxybutyrate (BHBA)', '3-indoxyl sulfate', '3-methyl-2-oxovalerate', '3-methylhistidine', '4-acetamidophenol', '4-acetaminophen sulfate', '4-androsten-3beta,17beta-diol disulfate (1)', '4-methyl-2-oxopentanoate', '5-methylthioadenosine (MTA)', '5-methyluridine (ribothymidine)', '5-oxoproline', '6-phosphogluconate', '7-alpha-hydroxy-3-oxo-4-cholestenoate (7-Hoca)', 'acetylcarnitine', 'adenine', 'adenosine', "adenosine 2'-monophosphate (2'-AMP)", "adenosine 3'-monophosphate (3'-AMP)", 'adrenate (22:4n6)', 'alanine', 'alanylleucine', 'alpha-hydroxyisovalerate', 'alpha-tocopherol', 'anserine', 'arachidonate (20:4n6)', 'arginine', 'ascorbate (Vitamin C)', 'asparagine', 'aspartate', 'beta-alanine', 'betaine', 'butyrylcarnitine', 'C-glycosyltryptophan', 'caprate (10:0)', 'carnitine', 'catechol sulfate', 'cholesterol', 'choline', 'phosphocholine', 'citrate', 'citrulline', 'creatine', 'creatinine', 'cysteine', 'cysteine-glutathione disulfide', 'cystine', 'cytidine', "cytidine 5'-diphosphocholine", 'deoxycarnitine', 'dihomo-linoleate (20:2n6)', 'dihomo-linolenate (20:3n3 or n6)', 'docosadienoate (22:2n6)', 'docosahexaenoate (DHA; 22:6n3)', 'docosapentaenoate (n3 DPA; 22:5n3)', 'docosapentaenoate (n6 DPA; 22:5n6)', 'eicosapentaenoate (EPA; 20:5n3)', 'eicosenoate (20:1)', 'ergothioneine', 'erythritol', 'erythronate', 'flavin adenine dinucleotide (FAD)', 'fructose', 'fumarate', 'gamma-glutamylglutamate', 'gamma-glutamylglutamine', 'gamma-glutamylisoleucine', 'gamma-glutamylleucine', 'gamma-glutamylphenylalanine', 'gamma-glutamylvaline', 'gluconate', 'glucose', 'glucose 6-phosphate', 'glutamate', 'glutamate, gamma-methyl ester', 'glutamine', 'glutarate (C5-DC)', 'glutathione, oxidized (GSSG)', 'glutathione, reduced (GSH)', 'glycerate', 'glycerol', 'glycerol 3-phosphate (G3P)', 'glycerophosphoethanolamine', 'glycerophosphorylcholine (GPC)', 'glycine', 'glycylleucine', 'guanine', 'guanosine', "guanosine 5'- monophosphate (5'-GMP)", 'heme', 'hexanoylcarnitine', 'hippurate', 'histamine', 'histidine', 'hypotaurine', 'hypoxanthine', 'inosine', 'inositol 1-phosphate (I1P)', 'isobutyrylcarnitine', 'isoleucine', 'isovalerylcarnitine', 'kynurenine', 'lactate', 'laurate (12:0)', 'leucine', 'leucylglycine', 'lidocaine', 'linoleate (18:2n6)', 'linolenate [alpha or gamma; (18:3n3 or 6)]', 'lysine', 'malate', 'maltose', 'maltotriose', 'mannose', 'mannose 6-phosphate', 'margarate (17:0)', 'methionine', 'methylphosphate', 'myo-inositol', 'myristate (14:0)', 'myristoleate (14:1n5)', 'N-acetyl-aspartyl-glutamate (NAAG)', 'N-acetylalanine', 'N-acetylaspartate (NAA)', 'N-acetylglucosamine 6-phosphate', 'N-acetylglycine', 'N-acetylmethionine', 'N-acetylneuraminate', 'N-acetylserine', 'N-acetylthreonine', '1-methyladenosine', 'N6-acetyllysine', 'nicotinamide', 'nicotinamide adenine dinucleotide (NAD+)', 'oleoylcarnitine', 'ophthalmate', 'ornithine', '4-acetamidophenylglucuronide', 'p-cresol sulfate', 'palmitate (16:0)', 'palmitoleate (16:1n7)', 'palmitoyl sphingomyelin (d18:1/16:0)', 'palmitoylcarnitine', 'pantothenate', 'pentadecanoate (15:0)', 'phenol sulfate', 'phenylacetylglutamine', 'phenylalanine', 'phosphate', 'phosphoethanolamine', 'pipecolate', 'proline', 'propionylcarnitine', 'pseudouridine', 'pyroglutamine', 'ribitol', 'ribose', 'S-adenosylhomocysteine (SAH)', 'S-methylcysteine', 'sedoheptulose-7-phosphate', 'serine', 'spermidine', 'sphinganine', 'sphingosine', 'stachydrine', 'stearate (18:0)', 'stearoyl sphingomyelin (d18:1/18:0)', 'stearoylcarnitine', 'succinate', 'taurine', 'theobromine', 'threonate', 'threonine', 'thymine', 'tryptophan', 'tryptophan betaine ', 'tyrosine', 'uracil', 'urate', 'urea', 'uridine', 'valine', 'valylglycine', 'xanthine', 'xanthosine', '3-phosphoglycerate', 'dehydroascorbate', 'pyruvate', 'phosphoenolpyruvate (PEP)']

#Metabolite prediction functions

In [ ]:
metabolite_names = pd.read_csv('drive/My Drive/Colab Notebooks/Metabolite_prediction_ML/Tissue_res/y_train_tissue_name_map.csv')
metabolite_names = metabolite_names.fillna('No_id')
metabolite_names

,Query,Match,HMDB,PubChem,ChEBI,KEGG,METLIN,SMILES,Comment
0,"1,5-anhydroglucitol (1,5-AG)",No_id,No_id,No_id,No_id,No_id,No_id,No_id,0
1,1-arachidonoyl-GPC (20:4n6),No_id,No_id,No_id,No_id,No_id,No_id,No_id,0
2,1-arachidonoyl-GPE (20:4n6),No_id,No_id,No_id,No_id,No_id,No_id,No_id,0
3,1-arachidonoyl-GPI (20:4),No_id,No_id,No_id,No_id,No_id,No_id,No_id,0
4,1-linoleoylglycerol (18:2),No_id,No_id,No_id,No_id,No_id,No_id,No_id,0
...,...,...,...,...,...,...,...,...,...
213,xanthosine,Xanthosine,HMDB0000299,64959.0,18107.0,C01762,3408.0,OC[C@H]1O[C@H]([C@H](O)[C@@H]1O)N1C=NC2=C1N=C(...,1
214,3-phosphoglycerate,3-Phosphoglyceric acid,HMDB0000807,724.0,17050.0,C00597,150.0,OC(COP(O)(O)=O)C(O)=O,1
215,dehydroascorbate,Dehydroascorbic acid,HMDB0001264,440667.0,27956.0,C05422,342.0,[H][C@@]1(OC(=O)C(=O)C1=O)[C@@H](O)CO,1
216,pyruvate,Pyruvic acid,HMDB0000243,1060.0,32816.0,C00022,117.0,CC(=O)C(O)=O,1
217,phosphoenolpyruvate (PEP),Phosphoenolpyruvic acid,HMDB0000263,1005.0,44897.0,C00074,5264.0,OC(=O)C(=C)OP(O)(O)=O,1

In [ ]:
metabolite_name_dict = dict(zip(metabolite_names['Query'], metabolite_names['HMDB']))
metabolite_name_dict

{'1,5-anhydroglucitol (1,5-AG)': 'No_id',
 '1-arachidonoyl-GPC (20:4n6)': 'No_id',
 '1-arachidonoyl-GPE (20:4n6)': 'No_id',
 '1-arachidonoyl-GPI (20:4)': 'No_id',
 '1-linoleoylglycerol (18:2)': 'No_id',
 '1-linoleoyl-GPC (18:2)': 'HMDB0010386',
 '1-oleoylglycerol (1-monoolein)': 'HMDB0011567',
 '1-oleoyl-GPE (18:1)': 'No_id',
 '1-palmitoleoyl-GPC (16:1)': 'No_id',
 '1-palmitoylglycerol (1-monopalmitin)': 'No_id',
 '1-palmitoyl-GPC (16:0)': 'HMDB0010382',
 '1-palmitoyl-GPE (16:0)': 'HMDB0011503',
 '1-palmitoyl-GPI (16:0)': 'No_id',
 '1-(1-enyl-palmitoyl)-GPE (P-16:0)': 'No_id',
 '1-stearoyl-GPC (18:0)': 'No_id',
 '1-stearoyl-GPI (18:0)': 'No_id',
 '10-heptadecenoate (17:1n7)': 'HMDB0060038',
 '10-nonadecenoate (19:1n9)': 'HMDB0013622',
 '13-HODE + 9-HODE': 'No_id',
 'methyl palmitate (15 or 2)': 'HMDB0061709',
 "2'-deoxyguanosine": 'HMDB0000085',
 "2'-deoxyinosine": 'HMDB0000071',
 '2-aminoadipate': 'HMDB0000510',
 '2-hydroxyglutarate': 'HMDB0059655',
 '2-hydroxypalmitate': 'HMDB0031057',
 '2-methylbutyroylcarnitine': 'HMDB0000378',
 '2-palmitoyl-GPC (16:0)': 'No_id',
 '3-(4-hydroxyphenyl)lactate': 'HMDB0000755',
 '3-aminoisobutyrate': 'HMDB0003911',
 '3-carboxy-4-methyl-5-propyl-2-furanpropanoate (CMPF)': 'HMDB0061112',
 '3-hydroxybutyrate (BHBA)': 'HMDB0000011',
 '3-indoxyl sulfate': 'HMDB0000682',
 '3-methyl-2-oxovalerate': 'HMDB0037114',
 '3-methylhistidine': 'HMDB0000479',
 '4-acetamidophenol': 'HMDB0001859',
 '4-acetaminophen sulfate': 'HMDB0059911',
 '4-androsten-3beta,17beta-diol disulfate (1)': 'HMDB0240313',
 '4-methyl-2-oxopentanoate': 'HMDB0000695',
 '5-methylthioadenosine (MTA)': 'HMDB0001173',
 '5-methyluridine (ribothymidine)': 'HMDB0000884',
 '5-oxoproline': 'HMDB0000267',
 '6-phosphogluconate': 'HMDB0001316',
 '7-alpha-hydroxy-3-oxo-4-cholestenoate (7-Hoca)': 'HMDB0012458',
 'acetylcarnitine': 'HMDB0000201',
 'adenine': 'HMDB0000034',
 'adenosine': 'HMDB0000050',
 "adenosine 2'-monophosphate (2'-AMP)": 'HMDB0000045',
 "adenosine 3'-monophosphate (3'-AMP)": 'HMDB0003540',
 'adrenate (22:4n6)': 'HMDB0002226',
 'alanine': 'HMDB0000161',
 'alanylleucine': 'HMDB0028691',
 'alpha-hydroxyisovalerate': 'HMDB0000407',
 'alpha-tocopherol': 'HMDB0001893',
 'anserine': 'HMDB0000194',
 'arachidonate (20:4n6)': 'HMDB0001043',
 'arginine': 'HMDB0000517',
 'ascorbate (Vitamin C)': 'HMDB0000044',
 'asparagine': 'HMDB0000168',
 'aspartate': 'HMDB0000191',
 'beta-alanine': 'HMDB0000056',
 'betaine': 'HMDB0000043',
 'butyrylcarnitine': 'HMDB0002013',
 'C-glycosyltryptophan': 'No_id',
 'caprate (10:0)': 'HMDB0000511',
 'carnitine': 'HMDB0000062',
 'catechol sulfate': 'HMDB0059724',
 'cholesterol': 'HMDB0000067',
 'choline': 'HMDB0000097',
 'phosphocholine': 'HMDB0001565',
 'citrate': 'HMDB0000094',
 'citrulline': 'HMDB0000904',
 'creatine': 'HMDB0000064',
 'creatinine': 'HMDB0000562',
 'cysteine': 'HMDB0000574',
 'cysteine-glutathione disulfide': 'HMDB0250707',
 'cystine': 'HMDB0250712',
 'cytidine': 'HMDB0000089',
 "cytidine 5'-diphosphocholine": 'HMDB0001413',
 'deoxycarnitine': 'HMDB0001161',
 'dihomo-linoleate (20:2n6)': 'HMDB0005060',
 'dihomo-linolenate (20:3n3 or n6)': 'HMDB0002925',
 'docosadienoate (22:2n6)': 'HMDB0061714',
 'docosahexaenoate (DHA; 22:6n3)': 'HMDB0002183',
 'docosapentaenoate (n3 DPA; 22:5n3)': 'HMDB0006528',
 'docosapentaenoate (n6 DPA; 22:5n6)': 'HMDB0001976',
 'eicosapentaenoate (EPA; 20:5n3)': 'HMDB0001999',
 'eicosenoate (20:1)': 'HMDB0002231',
 'ergothioneine': 'HMDB0003045',
 'erythritol': 'HMDB0002994',
 'erythronate': 'HMDB0000613',
 'flavin adenine dinucleotide (FAD)': 'HMDB0001248',
 'fructose': 'HMDB0000660',
 'fumarate': 'HMDB0000134',
 'gamma-glutamylglutamate': 'HMDB0011737',
 'gamma-glutamylglutamine': 'HMDB0011738',
 'gamma-glutamylisoleucine': 'HMDB0011170',
 'gamma-glutamylleucine': 'HMDB0011171',
 'gamma-glutamylphenylalanine': 'HMDB0000594',
 'gamma-glutamylvaline': 'HMDB0011172',
 'gluconate': 'HMDB0000625',
 'glucose': 'HMDB0000122',
 'glucose 6-phosphate': 'HMDB0001401',
 'glutamate': 'HMDB0000148',
 'glutamate, gamma-methyl ester': 'HMDB0061715',
 'glutamine': 'HMDB0000641',
 'glutarate (C5-DC)': 'HMDB0000661',
 'glutathione, oxidized (GSSG)': 'HMDB0003337',
 'glutathione, reduced (GSH)': 'HMDB0000125',
 'glycerate': 'HMDB0000139',
 'glycerol': 'HMDB0000131',
 'glycerol 3-phosphate (G3P)': 'HMDB0000126',
 'glycerophosphoethanolamine': 'HMDB0000114',
 'glycerophosphorylcholine (GPC)': 'HMDB0000086',
 'glycine': 'HMDB0000123',
 'glycylleucine': 'HMDB0000759',
 'guanine': 'HMDB0000132',
 'guanosine': 'HMDB0000133',
 "guanosine 5'- monophosphate (5'-GMP)": 'HMDB0001397',
 'heme': 'HMDB0003178',
 'hexanoylcarnitine': 'HMDB0000756',
 'hippurate': 'HMDB0000714',
 'histamine': 'HMDB0000870',
 'histidine': 'HMDB0000177',
 'hypotaurine': 'HMDB0000965',
 'hypoxanthine': 'HMDB0000157',
 'inosine': 'HMDB0000195',
 'inositol 1-phosphate (I1P)': 'HMDB0000213',
 'isobutyrylcarnitine': 'HMDB0000736',
 'isoleucine': 'HMDB0000172',
 'isovalerylcarnitine': 'HMDB0000688',
 'kynurenine': 'HMDB0000684',
 'lactate': 'HMDB0000190',
 'laurate (12:0)': 'HMDB0000638',
 'leucine': 'HMDB0000687',
 'leucylglycine': 'HMDB0000759',
 'lidocaine': 'HMDB0014426',
 'linoleate (18:2n6)': 'HMDB0000673',
 'linolenate [alpha or gamma; (18:3n3 or 6)': 'No_id',
 'lysine': 'HMDB0000182',
 'malate': 'HMDB0000156',
 'maltose': 'HMDB0000163',
 'maltotriose': 'HMDB0001262',
 'mannose': 'HMDB0000169',
 'mannose 6-phosphate': 'HMDB0001078',
 'margarate (17:0)': 'HMDB0002259',
 'methionine': 'HMDB0000696',
 'methylphosphate': 'HMDB0061711',
 'myo-inositol': 'HMDB0000211',
 'myristate (14:0)': 'HMDB0000806',
 'myristoleate (14:1n5)': 'HMDB0002000',
 'N-acetyl-aspartyl-glutamate (NAAG)': 'HMDB0001067',
 'N-acetylalanine': 'HMDB0000766',
 'N-acetylaspartate (NAA)': 'HMDB0000812',
 'N-acetylglucosamine 6-phosphate': 'HMDB0002817',
 'N-acetylglycine': 'HMDB0000532',
 'N-acetylmethionine': 'HMDB0011745',
 'N-acetylneuraminate': 'No_id',
 'N-acetylserine': 'HMDB0002931',
 'N-acetylthreonine': 'HMDB0062557',
 '1-methyladenosine': 'HMDB0003331',
 'N6-acetyllysine': 'HMDB0000197',
 'nicotinamide': 'HMDB0001406',
 'nicotinamide adenine dinucleotide (NAD+)': 'HMDB0000902',
 'oleoylcarnitine': 'HMDB0005065',
 'ophthalmate': 'HMDB0005765',
 'ornithine': 'HMDB0000214',
 '4-acetamidophenylglucuronide': 'HMDB0010316',
 'p-cresol sulfate': 'HMDB0011635',
 'palmitate (16:0)': 'HMDB0000220',
 'palmitoleate (16:1n7)': 'HMDB0003229',
 'palmitoyl sphingomyelin (d18:1/16:0)': 'HMDB0010169',
 'palmitoylcarnitine': 'HMDB0000222',
 'pantothenate': 'HMDB0000210',
 'pentadecanoate (15:0)': 'HMDB0000826',
 'phenol sulfate': 'HMDB0060015',
 'phenylacetylglutamine': 'HMDB0006344',
 'phenylalanine': 'HMDB0000159',
 'phosphate': 'HMDB0001429',
 'phosphoethanolamine': 'HMDB0000224',
 'pipecolate': 'HMDB0000070',
 'proline': 'HMDB0000162',
 'propionylcarnitine': 'HMDB0000824',
 'pseudouridine': 'HMDB0000767',
 'pyroglutamine': 'HMDB0062558',
 'ribitol': 'HMDB0000508',
 'ribose': 'HMDB0000283',
 'S-adenosylhomocysteine (SAH)': 'HMDB0000939',
 'S-methylcysteine': 'HMDB0002108',
 'sedoheptulose-7-phosphate': 'HMDB0258206',
 'serine': 'HMDB0000187',
 'spermidine': 'HMDB0001257',
 'sphinganine': 'HMDB0000269',
 'sphingosine': 'HMDB0000252',
 'stachydrine': 'HMDB0004827',
 'stearate (18:0)': 'HMDB0000827',
 'stearoyl sphingomyelin (d18:1/18:0)': 'HMDB0001348',
 'stearoylcarnitine': 'HMDB0000848',
 'succinate': 'HMDB0000254',
 'taurine': 'HMDB0000251',
 'theobromine': 'HMDB0002825',
 'threonate': 'HMDB0000943',
 'threonine': 'HMDB0000167',
 'thymine': 'HMDB0000262',
 'tryptophan': 'HMDB0000929',
 'tryptophan betaine': 'HMDB0061115',
 'tyrosine': 'HMDB0000158',
 'uracil': 'HMDB0000300',
 'urate': 'HMDB0000289',
 'urea': 'HMDB0000294',
 'uridine': 'HMDB0000296',
 'valine': 'HMDB0000883',
 'valylglycine': 'HMDB0029127',
 'xanthine': 'HMDB0000292',
 'xanthosine': 'HMDB0000299',
 '3-phosphoglycerate': 'HMDB0000807',
 'dehydroascorbate': 'HMDB0001264',
 'pyruvate': 'HMDB0000243',
 'phosphoenolpyruvate (PEP)': 'HMDB0000263'}

In [ ]:
def normalize(df):
  data = df.copy()
  min_val = np.min(data)
  max_val = np.max(data)
  data_scaled = 2 * ((data - min_val) / (max_val - min_val)) - 1
  data_scaled = data_scaled.astype(np.float32)
  print('min:', np.min(data_scaled))
  print('max:', np.max(data_scaled))
  print('shape:', data_scaled.shape)

  return data_scaled

In [ ]:
#Ensemble predictions

def predict_metabolites_ensemble(model_1, model_2, final_estimator, df, input_features, output_features, output_features_to_keep):
  df = df.reindex(input_features, axis = 'columns')
  pred_1 = model_1.predict(df)
  pred_2 = model_2.predict(df)
  stacked_preds = np.hstack([pred_1, pred_2])
  pred_metabolites = final_estimator.predict(stacked_preds)
  pred_metabolites = pd.DataFrame(pred_metabolites, index = df.index, columns = output_features)
  pred_metabolites = pred_metabolites.rename(columns = metabolite_name_dict)
  pred_metabolites = pred_metabolites.drop(columns = ['No_id'])
  pred_metabolites = pred_metabolites[output_features_to_keep]

  return pred_metabolites

In [ ]:
def nn_predict(model, df, input_features, output_features, output_features_to_keep):
  data = df.copy()
  data = data.reindex(input_features, axis = 'columns')
  data = normalize(data)
  data = pd.DataFrame(data, index = df.index, columns = input_features)

  predictions = model.predict(data)
  predictions = pd.DataFrame(predictions, index = data.index, columns = output_features)
  predictions = predictions.rename(columns = metabolite_name_dict)
  predictions = predictions.drop(columns = ['No_id'])
  predictions = predictions[output_features_to_keep]

  return predictions

#Metabolite prediction

In [ ]:
with open('drive/My Drive/Colab Notebooks/Deep_learning_metabolomics_prediction/results/total_metabolites_predicted.pkl', 'rb') as file:
  correct_mets = pickle.load(file)

correct_mets

{'Ensemble': ['HMDB0000870',
  'HMDB0000848',
  'HMDB0000714',
  'HMDB0000191',
  'HMDB0000251',
  'HMDB0003229',
  'HMDB0000562',
  'HMDB0000252',
  'HMDB0000696',
  'HMDB0000641',
  'HMDB0000827',
  'HMDB0000806',
  'HMDB0001316',
  'HMDB0000289',
  'HMDB0000162',
  'HMDB0000939',
  'HMDB0000262',
  'HMDB0000043',
  'HMDB0000156',
  'HMDB0000625',
  'HMDB0000532',
  'HMDB0003045',
  'HMDB0000139',
  'HMDB0000929',
  'HMDB0000826',
  'HMDB0002000',
  'HMDB0000159',
  'HMDB0011737',
  'HMDB0000086',
  'HMDB0006344',
  'HMDB0000210',
  'HMDB0000759',
  'HMDB0001348',
  'HMDB0000134',
  'HMDB0000300',
  'HMDB0000660',
  'HMDB0000071',
  'HMDB0011503',
  'HMDB0000812',
  'HMDB0001406',
  'HMDB0001173',
  'HMDB0000182',
  'HMDB0000517',
  'HMDB0000673',
  'HMDB0000695',
  'HMDB0028691'],
 'Deep_learning_unbiased_features': ['HMDB0000195',
  'HMDB0000064',
  'HMDB0000097',
  'HMDB0000177',
  'HMDB0000167',
  'HMDB0000224',
  'HMDB0000126',
  'HMDB0000254',
  'HMDB0000767',
  'HMDB0028691',
  'HMDB0000163',
  'HMDB0000684',
  'HMDB0000089',
  'HMDB0000939',
  'HMDB0011172',
  'HMDB0000201',
  'HMDB0000283',
  'HMDB0000211',
  'HMDB0001565',
  'HMDB0000943',
  'HMDB0000125',
  'HMDB0000123',
  'HMDB0000267',
  'HMDB0000299',
  'HMDB0000157',
  'HMDB0000168']}

In [ ]:
ensemble_metabolites = predict_metabolites_ensemble(model_1 = model_1,
                                                    model_2 = model_2,
                                                    final_estimator = final_estimator,
                                                    df = rna,
                                                    input_features = ensemble_features,
                                                    output_features = ensemble_y_train_features_loaded,
                                                    output_features_to_keep = correct_mets['Ensemble'])
ensemble_metabolites.head(3)

,HMDB0000870,HMDB0000848,HMDB0000714,HMDB0000191,HMDB0000251,HMDB0003229,HMDB0000562,HMDB0000252,HMDB0000696,HMDB0000641,...,HMDB0000071,HMDB0011503,HMDB0000812,HMDB0001406,HMDB0001173,HMDB0000182,HMDB0000517,HMDB0000673,HMDB0000695,HMDB0028691
604,18.438829,23.274426,22.081167,26.127812,23.131805,23.290812,25.931002,24.418532,24.269643,26.835526,...,16.458911,21.393120,20.316690,26.236305,22.806326,25.847431,29.390496,23.883118,18.951283,16.109297
01BR044,17.597011,23.972762,22.014926,26.743141,23.722936,23.807916,25.600114,24.474292,25.059188,26.773997,...,15.456681,20.661615,19.466565,26.491161,21.690087,26.328768,28.925082,24.209487,19.847988,15.891932
01BR001,17.179488,23.673430,22.454827,26.786691,23.265519,23.590685,25.502678,24.135192,25.298792,26.783509,...,15.698542,21.296630,19.896826,27.120033,21.635567,26.794844,29.328613,24.143398,19.775032,15.424480

In [ ]:
nn_metabolites = nn_predict(model = var_model,
                            df = rna,
                            input_features = var_model_input_features,
                            output_features = var_model_output_features,
                            output_features_to_keep = correct_mets['Deep_learning_unbiased_features'])
nn_metabolites.head(3)

min: -1.0
max: 1.0
shape: (121, 3030)
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

,HMDB0000195,HMDB0000064,HMDB0000097,HMDB0000177,HMDB0000167,HMDB0000224,HMDB0000126,HMDB0000254,HMDB0000767,HMDB0028691,...,HMDB0000283,HMDB0000211,HMDB0001565,HMDB0000943,HMDB0000125,HMDB0000123,HMDB0000267,HMDB0000299,HMDB0000157,HMDB0000168
604,0.073615,0.255076,0.213865,-0.049121,0.184575,0.012580,0.092436,0.055211,-0.266775,-0.337123,...,-0.200030,0.351633,0.201288,0.048132,-0.233729,0.354792,0.016786,-0.319308,0.031904,0.118464
01BR044,0.169780,0.426143,0.402143,0.034123,0.297797,0.125990,0.112846,0.145762,-0.217544,-0.346253,...,-0.186905,0.421679,0.371971,0.157202,-0.209707,0.418275,0.123919,-0.263619,0.152397,0.298434
01BR001,0.077431,0.260991,0.228859,-0.049399,0.187926,0.020073,0.102145,0.061170,-0.271964,-0.340934,...,-0.197350,0.358180,0.214143,0.050080,-0.240477,0.359375,0.020008,-0.318136,0.035126,0.130433

In [ ]:
from sklearn.preprocessing import MinMaxScaler

def min_max(df):
  data = df.copy()
  scaler = MinMaxScaler(feature_range=(-1, 1))
  data = scaler.fit_transform(data)
  data = pd.DataFrame(data, index = df.index, columns = df.columns)

  return data

ensemble_metabolites = min_max(ensemble_metabolites)
print(np.max(ensemble_metabolites), np.min(ensemble_metabolites))

nn_metabolites = min_max(nn_metabolites)
print(np.max(nn_metabolites), np.min(nn_metabolites))

1.0000000000000018 -1.0000000000000009
1.000000238418579 -1.0

In [ ]:
drop_mets = list(set(ensemble_metabolites.columns).intersection(set(nn_metabolites.columns)))
len(drop_mets)

2

In [ ]:
#Drop from predictions the NN metabolites tha are common - manual inspection of R2 and Spearman's for these showed higher values in Ensemble model
nn_metabolites = nn_metabolites.drop(columns = drop_mets)
display(nn_metabolites.head(3))

,HMDB0000195,HMDB0000064,HMDB0000097,HMDB0000177,HMDB0000167,HMDB0000224,HMDB0000126,HMDB0000254,HMDB0000767,HMDB0000163,...,HMDB0000283,HMDB0000211,HMDB0001565,HMDB0000943,HMDB0000125,HMDB0000123,HMDB0000267,HMDB0000299,HMDB0000157,HMDB0000168
604,0.781880,0.776686,0.740489,0.830033,0.747212,0.781509,0.448421,0.806132,0.877903,0.937030,...,0.951040,0.668872,0.721662,0.835582,0.739329,0.793280,0.798259,0.873707,0.796069,0.802429
01BR044,0.995357,1.000000,1.000000,1.000000,1.000000,1.000000,0.580074,1.000000,1.000000,0.819989,...,1.000000,0.993177,1.000000,1.000000,0.877270,1.000000,1.000000,1.000000,1.000000,1.000000
01BR001,0.790351,0.784407,0.761155,0.829464,0.754693,0.795944,0.511051,0.818891,0.865034,0.935330,...,0.961039,0.699182,0.742624,0.838518,0.700580,0.808203,0.804327,0.876364,0.801522,0.815568

In [ ]:
metabolites = pd.concat([ensemble_metabolites, nn_metabolites], axis = 'columns')
metabolites.head(3)

,HMDB0000870,HMDB0000848,HMDB0000714,HMDB0000191,HMDB0000251,HMDB0003229,HMDB0000562,HMDB0000252,HMDB0000696,HMDB0000641,...,HMDB0000283,HMDB0000211,HMDB0001565,HMDB0000943,HMDB0000125,HMDB0000123,HMDB0000267,HMDB0000299,HMDB0000157,HMDB0000168
604,0.080774,0.112110,-0.106448,-0.311112,-0.323997,-0.547143,0.147663,0.106699,-0.374712,-0.006108,...,0.951040,0.668872,0.721662,0.835582,0.739329,0.793280,0.798259,0.873707,0.796069,0.802429
01BR044,-0.386640,0.405421,-0.138896,0.240313,0.401273,0.052100,-0.019681,0.133946,0.101739,-0.037636,...,1.000000,0.993177,1.000000,1.000000,0.877270,1.000000,1.000000,1.000000,1.000000,1.000000
01BR001,-0.618466,0.279697,0.076585,0.279340,-0.159941,-0.199637,-0.068958,-0.031760,0.246329,-0.032762,...,0.961039,0.699182,0.742624,0.838518,0.700580,0.808203,0.804327,0.876364,0.801522,0.815568

In [ ]:
metabolites = metabolites.drop(columns = 'HMDB0000759') #annotation of metabolite names produce same HMDB ID, drop this
metabolites.head(3)

,HMDB0000870,HMDB0000848,HMDB0000714,HMDB0000191,HMDB0000251,HMDB0003229,HMDB0000562,HMDB0000252,HMDB0000696,HMDB0000641,...,HMDB0000283,HMDB0000211,HMDB0001565,HMDB0000943,HMDB0000125,HMDB0000123,HMDB0000267,HMDB0000299,HMDB0000157,HMDB0000168
604,0.080774,0.112110,-0.106448,-0.311112,-0.323997,-0.547143,0.147663,0.106699,-0.374712,-0.006108,...,0.951040,0.668872,0.721662,0.835582,0.739329,0.793280,0.798259,0.873707,0.796069,0.802429
01BR044,-0.386640,0.405421,-0.138896,0.240313,0.401273,0.052100,-0.019681,0.133946,0.101739,-0.037636,...,1.000000,0.993177,1.000000,1.000000,0.877270,1.000000,1.000000,1.000000,1.000000,1.000000
01BR001,-0.618466,0.279697,0.076585,0.279340,-0.159941,-0.199637,-0.068958,-0.031760,0.246329,-0.032762,...,0.961039,0.699182,0.742624,0.838518,0.700580,0.808203,0.804327,0.876364,0.801522,0.815568

In [ ]:
metabolites = pd.concat([breast_tpm_meta['PIK3CA_mutation'], metabolites], axis = 'columns')
metabolites.head(3)

,PIK3CA_mutation,HMDB0000870,HMDB0000848,HMDB0000714,HMDB0000191,HMDB0000251,HMDB0003229,HMDB0000562,HMDB0000252,HMDB0000696,...,HMDB0000283,HMDB0000211,HMDB0001565,HMDB0000943,HMDB0000125,HMDB0000123,HMDB0000267,HMDB0000299,HMDB0000157,HMDB0000168
604,0,0.080774,0.112110,-0.106448,-0.311112,-0.323997,-0.547143,0.147663,0.106699,-0.374712,...,0.951040,0.668872,0.721662,0.835582,0.739329,0.793280,0.798259,0.873707,0.796069,0.802429
01BR044,1,-0.386640,0.405421,-0.138896,0.240313,0.401273,0.052100,-0.019681,0.133946,0.101739,...,1.000000,0.993177,1.000000,1.000000,0.877270,1.000000,1.000000,1.000000,1.000000,1.000000
01BR001,0,-0.618466,0.279697,0.076585,0.279340,-0.159941,-0.199637,-0.068958,-0.031760,0.246329,...,0.961039,0.699182,0.742624,0.838518,0.700580,0.808203,0.804327,0.876364,0.801522,0.815568

In [ ]:
breast_tpm_meta.shape

(121, 60617)

In [ ]:
metabolites.shape

(121, 70)

In [ ]:
metabolites.to_csv(os.path.join(output_path, 'CPTAC_metabolites_ensemble_nn_predicted.csv'), index = True)